boostorg/geometry

test/algorithms/distance/test_distance_se_common.hpp

by BOOST_CHECK and BOOST_CHECK_CLOSE

[test][algorithms][distance] replace use of internal Boost.Test tools

---

test/strategies/douglas_peucker.cpp

platform portable and platform independent

[test][strategies][douglas peucker] make the unit test for this strategy

---

include/boost/geometry/geometry.hpp

[geometry] remove non-existent #include

---

include/boost/geometry/strategies/cartesian/buffer_join_round.hpp

Rename local variable so that it is more descriptive.

Fix: rename local variable

---

include/boost/geometry/strategies/cartesian/buffer_join_round.hpp

calculating number of interior points

[strategies][cartesian][buffer][join_round] optimize expression

---

test/util/range.cpp

This PR adds tests for `iterator_range<const pointer>` and `pair<const pointer>`.

Add tests for iterator_range<const pointer> and pair<const pointer>

---

include/boost/geometry/extensions/contrib/ttmath_stub.hpp

Add support for the `fmod()` free function.

Extensions: add ttmath support for fmod

---

test/strategies/douglas_peucker.cpp

* Make case ID argument the first argument of tester;
* Include a label in the case id;

Fix: testing of Douglas Peucker strategy

---

include/boost/geometry/strategies/spherical/area_huiller.hpp

[strategies][spherical][area][huiller] update the URL for one of the references

---

include/boost/geometry/algorithms/detail/is_simple/linear.hpp
include/boost/geometry/algorithms/detail/is_valid/complement_graph.hpp
include/boost/geometry/algorithms/detail/is_valid/multipolygon.hpp
include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
include/boost/geometry/algorithms/detail/overlay/copy_segment_point.hpp
include/boost/geometry/algorithms/detail/overlay/copy_segments.hpp
include/boost/geometry/algorithms/detail/overlay/follow.hpp
include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/overlay/segment_identifier.hpp
include/boost/geometry/algorithms/detail/overlay/traverse.hpp
include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
include/boost/geometry/algorithms/detail/relate/follow_helpers.hpp
include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
include/boost/geometry/algorithms/detail/ring_identifier.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/algorithms/detail/signed_size_type.hpp
include/boost/geometry/algorithms/detail/turns/compare_turns.hpp
test/algorithms/set_operations/test_get_turns_ll_invariance.hpp

As promissed, this PR replaces the signed_index_type type with signed_size_type in the whole library.
The header file is renamed accordingly.

Replace signed_index_type with signed_size_type.

---

doc/release_notes.qbk

functionality, solved tickets, bugfixes)

[doc][release notes] update release notes for 1.59 release (additional

---

include/boost/geometry/extensions/gis/projections/impl/pj_init.hpp

Is this what you had in mind, with regard to the TODO comment?

Split pj units at divisor, support fractional multipliers.

---

doc/release_notes.qbk

https://github.com/boostorg/website/pull/238

1.64.0 release notes : fix ticket link

---

doc/design_rationale.qbk

[doc] Document Axis Order convention

---

include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp
include/boost/geometry/index/detail/rtree/node/weak_dynamic.hpp

The free function was accepted and voted into C++20 (P0653R2).

Use to_address free function instead of pointer_traits member

---

include/boost/geometry/formulas/thomas_inverse.hpp
include/boost/geometry/strategies/geographic/distance_cross_track.hpp
include/boost/geometry/strategies/spherical/distance_cross_track_box_box.hpp
test/algorithms/distance/distance_geo_box_box.cpp

This PL proposes fixes in box-box and point-segment distance computation as well as one in thomas inverse formula.

Few fixes in distance computation

---

doc/release_notes.qbk
include/boost/geometry/algorithms/detail/envelope/areal.hpp
include/boost/geometry/algorithms/detail/envelope/implementation.hpp
include/boost/geometry/algorithms/detail/envelope/linear.hpp
test/algorithms/envelope_expand/envelope_on_spheroid.cpp

This PR fixes the bug reported on issue https://github.com/boostorg/geometry/issues/471.

Fix envelope polygon

---

include/boost/geometry/formulas/area_formulas.hpp
include/boost/geometry/srs/projections/impl/function_overloads.hpp
include/boost/geometry/srs/projections/impl/pj_gauss.hpp
include/boost/geometry/srs/projections/impl/pj_phi2.hpp
include/boost/geometry/srs/projections/impl/pj_tsfn.hpp
include/boost/geometry/srs/projections/proj/aitoff.hpp
include/boost/geometry/srs/projections/proj/bipc.hpp
include/boost/geometry/srs/projections/proj/gstmerc.hpp
include/boost/geometry/srs/projections/proj/healpix.hpp
include/boost/geometry/srs/projections/proj/isea.hpp
include/boost/geometry/srs/projections/proj/krovak.hpp
include/boost/geometry/srs/projections/proj/lagrng.hpp
include/boost/geometry/srs/projections/proj/lcc.hpp
include/boost/geometry/srs/projections/proj/mod_ster.hpp
include/boost/geometry/srs/projections/proj/omerc.hpp
include/boost/geometry/srs/projections/proj/stere.hpp
include/boost/geometry/util/math.hpp

This fixes issue https://github.com/boostorg/geometry/issues/491.

Add math::pow(), use it in geo area formula and projections.

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info_for_endpoint.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info_la.hpp

It seems that not all sides has to be calculated so this PR also adds an optimization for L/A case.

Make side calculation for linear endpoints clearer.

---

include/boost/geometry/formulas/differential_quantities.hpp
include/boost/geometry/formulas/karney_direct.hpp
include/boost/geometry/formulas/thomas_direct.hpp
include/boost/geometry/formulas/vincenty_direct.hpp
test/formulas/direct.cpp

Fix for https://github.com/boostorg/geometry/issues/450

Allow negative distance in direct formulas.

---

include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
include/boost/geometry/strategies/spherical/envelope_segment.hpp
test/algorithms/disjoint/disjoint_seg_box.cpp

Propose a fix for https://github.com/boostorg/geometry/issues/579

Fix disjoint(segment, box) in spherical_equatorial and geographic CS

---

include/boost/geometry/formulas/sjoberg_intersection.hpp
test/formulas/intersection.cpp
test/formulas/test_formula.hpp

This fixes issue https://github.com/boostorg/geometry/issues/612

Fix division by 0 in sjoberg intersection formula

---

include/boost/geometry/algorithms/detail/closest_feature/point_to_range.hpp
test/algorithms/distance/distance_se_pl_l.cpp

This PR proposes a fix for https://github.com/boostorg/geometry/issues/557

Fix distance pt-linestring for short segments

---

example/ml03_distance_formula.cpp

This pull request adds a simple example on how to use a formula (in this case, Karney's direct method).

Example: usage of distance formula

---

include/boost/geometry/formulas/karney_inverse.hpp
include/boost/geometry/util/math.hpp
include/boost/geometry/util/normalize_spheroidal_coordinates.hpp

Also add const& to math util arguments.

Move math::difference_angle() because it uses C++11 std::reminder.

---

include/boost/geometry/geometry.hpp

Refines #689
------
Thanks to @Mike-Devel for pointing that out in https://github.com/boostorg/geometry/pull/689#issuecomment-613523835

Correct #689 with check for C++14 support instead of C++11 features

---

include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_original_visitor.hpp

This is the follow up, it is shorter

[buffer] remove rescaling from the turn-in-original check

---

include/boost/geometry/index/detail/varray_detail.hpp

In C++03 mimic the trait with has_trivial_copy, has_trivial_assign and has_trivial_destructor.
This is a fix for https://github.com/boostorg/geometry/issues/709

[index] Use memcpy and memmove only if T is_trivially_copyable.

---

include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp

* caused a crash for non-rescaled code (currently protected by TEST_FAILURE)
* it made the `std::sort`, where it was used, instable and output rubbish (alternatively we could use `stable_sort`)
* plus some minor code refactoring

[overlay] Fix possible instabilities in sort_by_side

---

include/boost/geometry/index/detail/rtree/visitors/insert.hpp

Make index::detail::rtree::visitors::insert base class public

---

test/arithmetic/infinite_line_functions.cpp

Sorry, missed this one. Thanks for the report.

[test] remove call to removed test

---

doc/index/make_qbk.py
doc/quickref.xml
doc/src/docutils/tools/doxygen_xml2qbk/configuration.hpp
doc/src/docutils/tools/doxygen_xml2qbk/doxygen_xml2qbk.cpp
doc/src/docutils/tools/doxygen_xml2qbk/quickbook_output.hpp

This fixes: https://github.com/boostorg/geometry/issues/396

[doc] Fix long file names in reference by setting qbk section id.

---

.github/workflows/documentation.yml
.github/workflows/minimal-clang.yml
.github/workflows/minimal-gcc.yml
.github/workflows/minimal-msvc.yml

This is now required by GitHub.

[ci] Replace set-env with env. file in GitHub scripts.

---

include/boost/geometry/index/detail/serialization.hpp

Fix build in index serialization

---

doc/compiling.qbk

Remove detailed list of compilers and versions form the docs

---

doc/doxy/Doxyfile

Fix Documentation error in Area strategy

---

include/boost/geometry/algorithms/area_result.hpp
include/boost/geometry/algorithms/default_area_result.hpp

Fix #define directive convention in area_result.hpp and default_area_result.hpp

---

include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
test/algorithms/disjoint/disjoint_seg_box.cpp

This PR proposes a fix for https://github.com/boostorg/geometry/issues/851

Add missing case for geo segment-box disjoint

---

doc/concept/ring.qbk

Fixed ring concept non-existent header file

---

include/boost/geometry/algorithms/detail/overlay/overlay.hpp
include/boost/geometry/algorithms/detail/overlay/traversal_switch_detector.hpp

This documents traversal switch detector for purpose of #869 but it doesn't solve it yet.
It's clean-up only.

[traverse] modernize code and add documentation, make clusters const

---

include/boost/geometry/algorithms/detail/select_geometry_type.hpp
include/boost/geometry/util/sequence.hpp
test/algorithms/line_interpolate.cpp
test/geometries/boost_array_as_point.cpp
test/strategies/envelope_segment.cpp
test/util/algorithm.cpp

- fix warnings in tests
- add workaround (fix?) gcc-11 c++20 compilation error
- rename some utils

Various small fixes and improvements.

---

include/boost/geometry/algorithms/detail/direction_code.hpp
include/boost/geometry/algorithms/detail/overlay/approximately_equals.hpp
include/boost/geometry/algorithms/detail/overlay/get_clusters.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/policies/robustness/segment_ratio.hpp
include/boost/geometry/strategy/cartesian/side_non_robust.hpp
include/boost/geometry/util/math.hpp
test/algorithms/detail/approximately_equals.cpp
test/algorithms/overlay/get_clusters.cpp
test/algorithms/overlay/multi_overlay_cases.hpp
test/algorithms/set_operations/union/Jamfile
test/algorithms/set_operations/union/union_multi.cpp
test/algorithms/set_operations/union/union_other_types.cpp
test/robustness/overlay/areal_areal/general_intersection_precision.cpp
test/string_from_type.hpp

This PR is a continuation of  #901 which was first to be merged into the other branch, and it's pr declined, but later split off

fix: small fixes to support boost multiprecision and rational

---

include/boost/geometry/algorithms/detail/equals/implementation.hpp

After PR https://github.com/boostorg/geometry/pull/926
I propose to define collect_vectors type in `use_collect_vectors`, so at the same place where this version is is enabled for specific side strategy and `cs_tag`.
Furthermore there is no need to instantiate both versions of collect_vectors with `std::conditional` in `equals_by_collection_or_relate` so this PR changes that.

[equals] Define collect_vectors type in use_collect_vectors

---

include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp

This fixes circleci
https://app.circleci.com/pipelines/github/boostorg/geometry/257/workflows/00234789-5f80-4b23-9075-4c359ec83d11/jobs/15405

fix: define get_distance_measure by default

---

include/boost/geometry/algorithms/detail/sections/sectionalize.hpp

This PR removes the `#if defined(BOOST_GEOMETRY_USE_RESCALING)` condition from sectionalize, and makes the implementation shorter anyway.
This is the last real dependency on the define `BOOST_GEOMETRY_USE_RESCALING` and `BOOST_GEOMETRY_NO_ROBUSTNESS`, which means we can change the default somewhere (hopefully very soon) after this PR is merged.

[sectionalize] remove dependency on define

---

include/boost/geometry/index/detail/serialization.hpp

Fix for https://github.com/boostorg/geometry/issues/962

Fix rtree elements count check in serialization/load.

---

include/boost/geometry/algorithms/for_each.hpp

Check return value from fe_segment_range_with_closure in for_each.hpp

---

test/algorithms/disjoint/disjoint_point_box_geometry.cpp

Tests for issues: https://github.com/boostorg/geometry/issues/837 and https://github.com/boostorg/geometry/issues/982 after fix: https://github.com/boostorg/geometry/pull/990

[test][disjoint] Add tests for box vs open ring.

---

include/boost/geometry/algorithms/detail/overlay/overlay.hpp

Fixes #443 and (IMHO) slightly improves clarity.

Fixes warning with -Wduplicated-branches in overlay for union (issue #443).

---

include/boost/geometry/strategies/cartesian/buffer_end_round.hpp
include/boost/geometry/strategies/cartesian/buffer_join_miter.hpp
include/boost/geometry/strategies/cartesian/buffer_join_round.hpp
include/boost/geometry/strategies/cartesian/buffer_join_round_by_divide.hpp
include/boost/geometry/strategies/cartesian/buffer_side_straight.hpp
test/strategies/Jamfile
test/strategies/buffer_join.cpp
test/strategies/buffer_side_straight.cpp

This fixes issue #998 
A similar issue was found in two other strategies.
Unit tests are added (apart from the fix for miter)

[buffer] fix for integer overflow

---

include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp

This fixes compilation errors when output point type is different.
The issue was caused by this PR: https://github.com/boostorg/geometry/pull/1027

[buffer] Use output_point_type with helper geometries instead of model::point

---

doc/release_notes.qbk

I realize it's too late (release is scheduled today), I was earlier confused about release date.
Anyway, I still think it's good to have these changes listed, even though they will be released in 1.81

[readme] update to reflect changes in 1.80

---

include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
include/boost/geometry/strategies/buffer.hpp
include/boost/geometry/strategies/cartesian/buffer_end_flat.hpp
include/boost/geometry/strategies/cartesian/buffer_end_round.hpp
include/boost/geometry/strategies/cartesian/buffer_join_round.hpp
include/boost/geometry/strategies/cartesian/buffer_point_circle.hpp
include/boost/geometry/strategies/geographic/buffer_end_round.hpp
include/boost/geometry/strategies/geographic/buffer_helper.hpp
include/boost/geometry/strategies/geographic/buffer_join_miter.hpp
include/boost/geometry/strategies/geographic/buffer_join_round.hpp
include/boost/geometry/strategies/geographic/buffer_point_circle.hpp
include/boost/geometry/strategies/geographic/buffer_side_straight.hpp
test/algorithms/buffer/buffer_polygon.cpp

[buffer] harmonize geographic strategy code and share code

---

include/boost/geometry/formulas/area_formulas.hpp
test/algorithms/area/area_sph_geo.cpp

This PR proposes a fix for https://github.com/boostorg/geometry/issues/1063

Fix special case of area for segments that pass through a pole.

---

include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp
test/algorithms/relate/Jamfile
test/algorithms/relate/relate_const_custom.cpp
test/test_geometries/const_point.hpp
test/test_geometries/custom_cartesian_point.hpp

Fixes https://github.com/boostorg/geometry/issues/1088

Fix mutable point issue and typos in boundary_checker.

---

include/boost/geometry/index/detail/rtree/linear/redistribute_elements.hpp
include/boost/geometry/index/detail/rtree/rstar/redistribute_elements.hpp
include/boost/geometry/index/rtree.hpp

Fix for https://github.com/boostorg/geometry/issues/1048

[index] Fix dangling references when Indexable is returned by value by IndexableGetter.

---

example/c03_custom_linestring_example.cpp
example/ml02_distance_strategy.cpp

Fix https://github.com/boostorg/geometry/issues/1104 (also fix another issue in examples).

Fix two issues in examples 

---

doc/release_notes.qbk
include/boost/geometry/algorithms/detail/direction_code.hpp
include/boost/geometry/algorithms/detail/make/make.hpp
include/boost/geometry/algorithms/detail/overlay/append_no_dups_or_spikes.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
test/geometries/custom_non_copiable/Jamfile
test/geometries/custom_non_copiable/custom_different_geometries.cpp
test/geometries/custom_non_copiable/helper_functions.hpp

This fixes #1139 , and more required code changes.
Including unit test.

[fix] support different geometry types

---

include/boost/geometry/index/detail/rtree/query_iterators.hpp
test/views/reversible_closeable.cpp

This PR fixes several warnings and compile errors. ~It also upgrades circleCI docker image.~

Several fixes of errors and warnings

---

include/boost/geometry/algorithms/centroid.hpp
include/boost/geometry/algorithms/detail/has_self_intersections.hpp
include/boost/geometry/algorithms/detail/overlay/inconsistent_turns_exception.hpp
include/boost/geometry/core/exception.hpp
include/boost/geometry/extensions/gis/io/shapefile/read.hpp
include/boost/geometry/extensions/gis/io/shapelib/shape_creator.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp
include/boost/geometry/io/wkt/read.hpp
include/boost/geometry/srs/projections/exception.hpp
include/boost/geometry/srs/projections/str_cast.hpp

Replace virtual with override in exception::what()

---

include/boost/geometry/core/config.hpp
include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
include/boost/geometry/strategy/cartesian/side_robust.hpp
test/geometry_test_common.hpp

feat: make side strategy configurable

---

test/algorithms/overlay/overlay.cpp
test/core/assert.cpp

Fixes 2 unit tests which were broken in my previous two PR's (each one broke one)

test: fix unit test failures
