include/boost/geometry/iterators/detail/segment_iterator/range_segment_iterator.hpp

This PR is about two fixes:
* Declare the `range_segment_iterator` as a class so as to match the friend declaration inside it (to avoid relevant warning)
* Fix bug in initialization of the `m_has_less_than_two_elements` boolean member variable for open ranges. When the range is open (e.g., when the range is a open ring, or one of the rings of an open polygon), the actual size of the range is increased by one (due to the closing iterator). So whether the actual (equivalent closed) range has less than 2 elements amounts to asking whether the original range is empty (has less then 1 element).

Fixes for range segment iterators

---

include/boost/geometry/strategies/cartesian/side_by_triangle.hpp

MSVC thinks that that the `detail::equals` namespace qualifying the call to `equals_point_point` is a nested namespace inside `boost::geometry::strategy::side`.
Fix: qualify the call to `equals_point_point` by `geometry::detail::equals`.

Fix MSVC error regarding undiscovered function equals_point_point

---

include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp

The assertion failure that is replaced indicates that something went wrong in the turns' computation, and more precisely that the turns computed are not consistent; such a case should better be handled by throwing an exception rather than an assertion.

Fix: replace assertion by exception

---

include/boost/geometry/algorithms/convert.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/algorithms/not_implemented.hpp
include/boost/geometry/core/interior_type.hpp
include/boost/geometry/core/ring_type.hpp
include/boost/geometry/geometries/adapted/boost_fusion.hpp
include/boost/geometry/strategies/comparable_distance_result.hpp
include/boost/geometry/strategies/distance_result.hpp
include/boost/geometry/util/combine_if.hpp
include/boost/geometry/util/compress_variant.hpp
include/boost/geometry/util/transform_variant.hpp

Boost.Geometry library); fix long lines produced by the addition of "boost::"

[geometry] qualify mpl:: namespace by boost:: (namespace external to the

---

include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp

Change access of a ring's front range element from using the `.front()` method by the `range::front` Boost.Geometry utility function.

Fix: replace access method for accessing the front element of rings

---

include/boost/geometry/geometries/variant.hpp

When variant types are generated from MPL sequences the actual variant
type is `boost::variant<over_sequence<Sequence...`
and thus T0 is `over_sequence<>`. This fix use the first bounded type `boost::variant<>::types`
instead of T0.

Fix point_type traits for variant over MPL sequence

---

include/boost/geometry/strategies/cartesian/buffer_point_circle.hpp

for small input values (less than 3): when the input point count is less
than 3, set the internal point count to 3; this is important for generating
valid polygons;

[strategies][cartesian][buffer][point_circle] fix internal point count

---

include/boost/geometry/algorithms/detail/within/point_in_geometry.hpp
include/boost/geometry/util/range.hpp

`*(--boost::end(rng));` is not valid for range with raw pointer as iterator (the compiler complains that `'--' needs l-value`. Since the range is supposed to be BidirectionalRange, use `*rbegin()` instead. See [PR#235](https://github.com/boostorg/geometry/pull/235) for the full description and discussion.

Fix range back() function

---

include/boost/geometry/strategies/cartesian/buffer_end_round.hpp

for small input values (less than 4): when the input point count is less
than 4, set the internal point count to 4; for values less than 4 the
generated ends do not look round;

[strategies][cartesian][buffer][end_round] fix internal point count

---

include/boost/geometry/strategies/cartesian/buffer_join_round.hpp

Make sure that at least one interior point is generated by the strategy.

Fix number of generated points in join_round buffer strategy

---

include/boost/geometry/iterators/point_iterator.hpp
include/boost/geometry/iterators/point_reverse_iterator.hpp

Fix `point_iterator` (and adapt `reverse_point_iterator` to the fix) to support linestrings/rings implemented with raw pointer as iterator. The issue can be reproduced with:
```
boost::iterator_range<const point_t *> l;
points_begin(l);
```
The compiler complain that `const point_t *` is not a legal base class of `point_iterator`.
The fix uses `boost::iterator_adaptor` that implements base() a synonyme of base_ptr() that consequently has been removed. The operators are also redondant and removed.

Fix point_iterator with raw pointer base

---

include/boost/geometry/algorithms/detail/not.hpp
include/boost/geometry/algorithms/equals.hpp

Modify the implementation of `detail::not_` by moving the geometry template parameters inside the class.
This way it is simpler to use `detail::not_` as it is not required to specify the geometries.

Simplify detail::not_

---

include/boost/geometry/util/math.hpp

Implement workaround for 32-bit platforms for which `sqrt(NaN)` returns a finite value instead of `NaN`. Workaround is activated by defining the macro `BOOST_GEOMETRY_SQRT_CHECK_FINITENESS`.
I would like this PR to become part of 1.58.

Workaround for sqrt for some 32-bit platforms

---

include/boost/geometry/util/range.hpp

This PR fixes `range::at()`, `range::front()` and `range::back()` with Ranges (such as `iterator_range<>`) that does not handle constness like containers.
This PR is a followup of [PR#245](https://github.com/boostorg/geometry/pull/245).

[range] Use range_reference

---

test/algorithms/distance/distance_areal_areal.cpp
test/algorithms/distance/distance_linear_areal.cpp
test/algorithms/distance/distance_linear_linear.cpp
test/algorithms/distance/distance_pointlike_areal.cpp
test/algorithms/distance/distance_pointlike_linear.cpp
test/algorithms/distance/distance_pointlike_pointlike.cpp
test/algorithms/distance/test_distance_common.hpp

In this PR:
* The common distance testing code has been re-factored and polished.
* It is now allowed to check test cases where the distance computed is not a finite floating-point number.
* Added a test case where the distance overflows.
* Added a test case where the distance computed is a `NaN`.

Distance: re-factor, polish and add new test cases

---

test/geometry_test_common.hpp

In this PR I guard the inclusion of Unit.Test related include by the macro `BOOST_TEST_MODULE`.
This macro is defined in many unit tests (distance, set-ops, validity, simplicity and possibly others), and is used for using Boost.Test is a different way than in traditionally written unit tests.
When `<geometry_test_common.hpp>` is included in those tests, the `test_main()` function is defined twice and gives a compilation error.
With the guarding proposed in this PR, `<geometry_test_common.hpp>` can be safely included in those unit tests as well, without any problems.

Fix: allow geometry test common to be included in all unit tests

---

doc/src/docutils/tools/support_status/support_status.cpp

This PR is about two issues:
* Removal of deprecated includes referring to the `include/boost/geometry/multi/` directory
* Fixes the support status call for `num_points`: `dispatch::num_points<>` takes a second boolean argument
with no default value, which was not accounted for by support status.
This PR may be merged independently or other PRs I have created.

Remove deprecated include paths - Part III & fix support status for num_points

---

test/algorithms/set_operations/difference/difference_pl_pl.cpp
test/algorithms/set_operations/intersection/intersection_pl_pl.cpp
test/algorithms/set_operations/union/union_pl_pl.cpp

This is a follow up PR of #264, that fixes the include paths of files modified in PR #256.
It has been created separately so as to avoid any potential merge conflicts.
This PR must be merged after PR #256 and PR #264 are merged.
I have already tested that merging PR #256, PR #264 and this PR in that order does not produce any conflicts.

Fix: remove deprecated include paths - Part II

---

include/boost/geometry/strategies/cartesian/cart_intersect.hpp

Compare both ratios' potential denominators, corresponding to both
segments. Furthermore, take into account the machine epsilon.
Without this change an assertion `ratio.denominator() != 0` can fail in intersection_points.hpp line 62, in segments_intersection_points policy. And indeed it fails e.g. in get_turns_linear_linear.cpp unit test if compiled in MinGW with -O2.
Furthermore, if compiled with -O2, the tests which "normally" was passing fails. Some of those cases are fixed if the denominators are compared WRT machine epsilon.
However not all of them. AFAIU the reason is different and related to the way how the determinant is calculated. See this PR: https://github.com/boostorg/geometry/pull/259 and this ticket: https://svn.boost.org/trac/boost/ticket/8379.

[strategies][cart_intersect] Compare ratios denominators consistently.

---

include/boost/geometry/extensions/contrib/ttmath_stub.hpp

The following simple program fails:
```
#include <boost/geometry/extensions/contrib/ttmath_stub.hpp>
template <typename T>
void f(T const&, T const&)
{
}
template <typename T>
void test()
{
T one(1.0);
f(one + one, one);
f(one * one, one);
f(one / one, one);
}
int main()
{
test<ttmath_big>();
return 0;
}
```
The reason is that the result of `operator+`, `operator*` and `operator-` is an object of type `::ttmath::Big<1,4>` instead of `::ttmath_big` (`::tmath_big` inherits from `::ttmath::Big<1,4>`).
In this PR I define the missing operators, as well as the unary `operator+` (for completeness) so that the bug above is gone.
This PR should be merged after boost 1.58 is released so that we won't have to worry about extensions right now.

Extensions: define ttmath big missing arithmetic operators

---

doc/release_notes.qbk
include/boost/geometry/policies/relate/intersection_points.hpp
include/boost/geometry/util/promote_integral.hpp
test/algorithms/overlay/overlay_cases.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/intersection/intersection.cpp
test/string_from_type.hpp
test/util/Jamfile.v2
test/util/promote_integral.cpp

This PR addresses Boost [Trac Ticket #10835](https://svn.boost.org/trac/boost/ticket/10835).
The problem reported in the ticket was due to overflow in integer operations when the intersections points (for the second linear/areal difference) were computed.
The way the problem is addressed in this PR is by promoting the integral coordinates to another integral type of larger size, for which overflow does not happen; the outcome of the arithmetic operations with the promoted integral type is then cast back to the original integral type.
On a technical level, to perform this promotion, a new meta-function `promote_integral<>` has been implemented. This meta-function promotes a fundamental integral type `T` to a another integral type (possibly a multi-precision one) with size twice the size of …

Fix for Boost Trac tickets #10658, #10835 and #11121

---

include/boost/geometry/util/promote_integral.hpp
test/util/promote_integral.cpp

In this PR:
* The inline documentation for `promote_integral<>` is updated.
* All size measurements are done in bits (rather than mixing bits and bytes).
* Code is polished a bit.
* Choice for the promoted type is based on bit size rather than on the outcome of the `sizeof()` operator.

A few updates for promote_integral

---

include/boost/geometry/util/promote_integral.hpp
test/util/promote_integral.cpp

This PR disables (by default) the use of `boost::int128_type` and `boost::uint128_type`. The use of these types can be enabled by defining the macro `BOOST_GEOMETRY_ENABLE_INT128`.

Disable use of int128

---

include/boost/geometry/util/math.hpp

Add support for calls to `boost::geometry::math::fmod`.
* For floating-point numbers it calls `std::fmod`.
* For fundamental integral numbers it calls `operator%`.
* For user defined number types the free function `fmod` is called (lookup is activated in the global namespace, the `std` namespace and the type's namespace.

Feature : support for fmod free function from within the math namespace

---

include/boost/geometry/extensions/gis/geographic/strategies/dms_parser.hpp
include/boost/geometry/extensions/gis/projections/proj/hatano.hpp
include/boost/geometry/extensions/gis/projections/proj/mbtfpp.hpp

This should fix several tests on Android and SunOS platforms where CS is a macro name.

Rename occurrences of CS in extensions.

---

test/algorithms/set_operations/difference/difference_pl_pl.cpp
test/algorithms/set_operations/intersection/intersection_pl_pl.cpp
test/algorithms/set_operations/test_set_ops_pointlike.hpp
test/algorithms/set_operations/union/union_pl_pl.cpp

In this PR:
* polish tests of set operations for pointlike/pointlike geometries (make the case ID the first argument of the tester)
* modify the common set operations test code so that it can be applied to set operations of pointlike/linear geometries as well

Unit tests for set operations of pointlike/pointlike geometries

---

include/boost/geometry/algorithms/detail/partition.hpp

The current `partition<>` implementation, the one or two input collections passed are assumed internally to be random access containers (to be precise, it is required that the collection's `operator[]` is defined).
In fact, this is requirement is a bit too strict. `partition<>` can easily work even for forward ranges, and this is the focus of this PR.
In this PR, `partition<>` has been modified so as to work for forward ranges. This eliminates among other things the need for the range to define `operator[]`. The idea behind the re-implementation is as follows: instead of storing and keeping track of indices of collection items (these are the indices that are used as arguments in `operator[]` calls), iterators to collection items are stored and manipulated. The `index_vector_type` is …

Fix: make partition work for forward ranges

---

include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/distance/geometry_to_segment_or_box.hpp
include/boost/geometry/algorithms/detail/is_valid/has_duplicates.hpp
include/boost/geometry/iterators/flatten_iterator.hpp

The proposed changes are workarounds, the code compiles on other platforms. Though I think merging them could be beneficient. Plus, there would be more green in the matrix.
There are a few more failing tests for which workarounds (2 issues) could be added:
* Spherical [distance](http://www.boost.org/development/tests/develop/developer/output/oracle-intel-S2-stlport4-boost-bin-v2-libs-geometry-test-algorithms-distance-distance_se_pl_pl-test-sun-stlport4-release-address-model-32-architecture-x86-threading-multi.html) tests - the use of `comparable_type` private member in the definition of public member struct template `haversine<>::calculation_type<>`, it's hard to believe that this fails only in haversine.
* [point_iterator](http://www.boost.org/development/tests/develop/developer/output/or …

Workarounds for SunOS

---

include/boost/geometry/geometries/box.hpp
include/boost/geometry/geometries/point.hpp

If `BOOST_GEOMETRY_ENABLE_ACCESS_DEBUGGING` is defined getters and setters checks if the data being read was properly initialized and if the object was properly created and wasn't destroyed.
With this change it's easy to detect e.g. the use of references to destroyed temporaries or the use of uninitialized objects.

Detection of access to uninitialized or destroyed geometries.

---

extensions/test/gis/io/wkb/read_wkb.cpp
extensions/test/gis/io/wkb/write_wkb.cpp
include/boost/geometry/extensions/gis/io/wkb/detail/ogc.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/writer.hpp
include/boost/geometry/extensions/gis/io/wkb/write_wkb.hpp

This patchset adds support for writing to the WKB format from geometries. There are a couple of fixes to support geometry adaptions there as well, and I had to modify the geometry_type to support different dimensions and formats.
This implementation is generic enough to be able to support CIRCULARSTRING, implemented on top of this implentation locally, so it should be sufficiently user-extendable for some use cases.
Current limitations: 
* endian conversion is not supported (yet)
* there might be some use of C++11 in there, which I will remove when the direction of this PR
* no support for multi-geometries (yet)
* there might be traces of CIRCULARSTRING left.
I am prepared to do more work to get this patch into Boost.Geometry proper, as it is a hassle to maintain this out-of-tree. :)

Add support for writing geometries to WKB

---

include/boost/geometry/arithmetic/arithmetic.hpp
test/algorithms/centroid.cpp
test/algorithms/test_centroid.hpp

The intention of this PR is to fix this ticket: https://svn.boost.org/trac/boost/ticket/11236
In this particular case, at the end of centroid calculation the resulting point is moved using the origin (taken from the input geometry). The point arithmetic functions internally was calculating the results using always the type of the second operand (in one of the STL binary predicates like `std::plus`). In this particular case the resulting Point is using coordinates of type `double` and the input Polygon coordinates of type `int`. `bg::add_point()` internally calls `std::plus<int>` which truncates the `double` value before addition. Ths PR changes it by using the more precise type.

Fix point arithmetic functions and centroid

---

include/boost/geometry/io/wkt/write.hpp

Instead of calling `geometry::disjoint()` from within `wkt/write.hpp`, call `geometry::detail::disjoint::disjoint_point_point()` instead. This reduces the dependency on the `geometry::disjoint()` algorithm and avoids potential circular dependencies.

Reduce dependency on geometry::disjoint algorithm

---

include/boost/geometry/extensions/contrib/ttmath_stub.hpp
include/boost/geometry/strategies/cartesian/buffer_end_round.hpp
include/boost/geometry/strategies/cartesian/buffer_join_round.hpp
include/boost/geometry/strategies/cartesian/buffer_point_circle.hpp
include/boost/geometry/strategies/spherical/area_huiller.hpp
include/boost/geometry/util/math.hpp

This PR:
* Adds to more constants in `boost::geometry::math` namespace: `2*π` and `π/2`.
* `ttmath_big` and `ttmath::Big<Exponent, Mantissa>` are modified to support these two new constants.
* Strategies that compute these two constants via `math::pi<>()`, now use the corresponding functions directly.

Add two-pi and half-pi constants

---

doc/release_notes.qbk

Add release notes for new funcitonality for 1.59:
* `intersection(pointlike, linear)`
* `difference(pointlike, linear)`

Doc: update release notes for 1.59

---

include/boost/geometry/algorithms/detail/overlay/clip_linestring.hpp
include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
test/algorithms/set_operations/intersection/intersection.cpp

This PR solves the issue reported in [Boost Trac Ticket 11268](https://svn.boost.org/trac/boost/ticket/11268).
The problem was that the function `detail::intersection::clip_range_with_box()` was passed a different number of arguments that the one the function was expecting.
**Fix:** the function, as well as those calling it, hve been modified to expect (respectively, pass) the correct number of arguments.

Fix for Boost Trac Ticket 11268

---

include/boost/geometry/extensions/gis/projections/project_inverse_transformer.hpp

The call to point_to_point was using the wrong namespace and function call.

[projections] fix project_inverse_transformer::apply

---

include/boost/geometry/core/radian_access.hpp
include/boost/geometry/strategies/spherical/distance_cross_track.hpp
include/boost/geometry/strategies/strategy_transform.hpp
include/boost/geometry/strategies/transform/matrix_transformers.hpp
include/boost/geometry/util/math.hpp
test/algorithms/distance/distance_se_pl_l.cpp
test/algorithms/distance/distance_se_pl_pl.cpp
test/algorithms/transform.cpp
test/strategies/vincenty.cpp

In this PR I modify the implementation of `degree_radian_converter` to use conversion constants that are consistent with the coordinate type of the geometry passed to the converter.
This is important for keeping the accuracy of user-defined number types (e.g., `ttmath`).

Fix degree_radian_converter

---

include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
include/boost/geometry/algorithms/detail/buffer/get_piece_turns.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
include/boost/geometry/strategies/cartesian/side_of_intersection.hpp

The intention of this PR is to:
- provide a temporary fix for msvc-8.0 caused by the use of Multiprecision. It replaces Multiprecision `cpp_int` with manually implemented solution.
- suppress some compiler warnings.

Buffer fixes.

---

include/boost/geometry/algorithms/centroid.hpp
include/boost/geometry/algorithms/convex_hull.hpp
include/boost/geometry/algorithms/detail/envelope/linestring.hpp
include/boost/geometry/algorithms/detail/overlay/overlay.hpp
include/boost/geometry/algorithms/detail/throw_on_empty_input.hpp
include/boost/geometry/io/svg/svg_mapper.hpp
test/algorithms/set_operations/union/test_union.hpp
test/algorithms/test_convex_hull.hpp
test/robustness/overlay/buffer/recursive_polygons_buffer.cpp

This PR replaces instances of `bg::num_points() == 0` by `bg::is_empty()` and instances of `bg::num_points() > 0` by `! bg::is_empty()`.
This is done both in the `include` and `test` directories.

Replace use of num_points by is_empty

---

include/boost/geometry/algorithms/detail/get_left_turns.hpp
include/boost/geometry/algorithms/detail/occupation_info.hpp
include/boost/geometry/algorithms/detail/overlay/copy_segments.hpp
include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/enrichment_info.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/strategies/cartesian/buffer_join_round.hpp

This affects buffer, overlay, relate and sectionalize.
Please for now treat `signed_index_type` and `signed_size_type` as one type. I still plan to replace the former with the latter consistently in the whole library. This is not the intention of this PR.

Replace int with more suitable type (std::size_t, signed_size_type, template parameter).

---

include/boost/geometry/strategies/spherical/distance_cross_track.hpp

(same as for projected_point distance strategy)

[strategies][distance][cross track] expose the radius type as a typedef

---

include/boost/geometry/extensions/contrib/ttmath_stub.hpp

Consider the following two programs.
```
#include <boost/geometry/extensions/contrib/ttmath_stub.hpp>
template <typename T>
T f(T const& x)
{
return T(2.0) * cos(x);
}
int main()
{
ttmath_big x = 0.5;
f(x);
return 0;
}
```
```
#include <boost/assert.hpp>
#include <boost/geometry/util/math.hpp>
#include <boost/geometry/extensions/contrib/ttmath_stub.hpp>
namespace math = boost::geometry::math;
int main()
{
ttmath_big half_pi = math::half_pi<ttmath_big>();
ttmath_big deg = 90;
ttmath_big d2r = math::pi<ttmath_big>() / ttmath_big(180);
ttmath_big rad = deg * d2r;
BOOST_ASSERT(math::equals(half_pi, rad));
return 0;
}
```
The first program fails at compile time. The reason is that the currently implemented `ttmath`-related math functions are implemented only for `ttmath::Big<Exponent, …

Extensions: fixes for ttmath::Big<Exponent, Mantissa> and ttmath_big

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
include/boost/geometry/strategies/cartesian/cart_intersect.hpp

The optimization is based on the fact that in the most cases the segments
handled in the `TurnInfoPolicy` are disjoint. For disjoint segments first
the points are rescaled, then the test for disjoint is run, next the
`TurnInfoPolicy` just returns and the next pair of segments is handled.
Therefore to optimze the `get_turns()` this commit changes two things:
1. the `cart_intersect` strategy may return just after the calculation of sides
for the first segment (2 sides calculation instead of 4),
2. the points are rescaled only one time in the intersection_helper,
already rescaled points are passed into the intersection strategy
I tested it using the MultiPoint `buffer()`. For only some fraction of the tests (all basic tests and 2 first tests from the `test_many_points_per_circle`, because I …

[get_turns][strategies] Optimize get_turns().

---

include/boost/geometry/algorithms/detail/is_valid/has_spikes.hpp
test/algorithms/is_simple.cpp
test/algorithms/is_valid.cpp

If the range passed to `has_spikes` consists of points with `NaN` coordinates (this can happen if the range passed as been computed as the result, e.g., of a set operation), then `has_spikes` can enter an infinite loop.
If a point `p` has such `NaN` coordinates, then `p` is considered as not equal to itself, a property/feature assumed in the previous implementation of `has_spikes`), and the following calls (in the older version of `has_spikes`) to `std::find_if` never return:
```
std::find_if(prev, boost::end(view), not_equal(*prev));
```
and
```
std::find_if(cur, boost::end(view), not_equal(*cur));
```
The solution if to essentially call `std::find_if` as `std::find_if(second, first, last, not_equal(*first))`, which avoids the implicit assumption that the `bg::equals(*first, *first)` …

Fix: possible infinite loop in has_spikes

---

include/boost/geometry/algorithms/detail/disjoint/box_box.hpp
include/boost/geometry/algorithms/detail/disjoint/point_box.hpp
include/boost/geometry/algorithms/detail/expand_by_epsilon.hpp
include/boost/geometry/algorithms/detail/overlay/intersection_box_box.hpp
include/boost/geometry/algorithms/detail/sections/section_functions.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/algorithms/overlaps.hpp
include/boost/geometry/algorithms/touches.hpp
include/boost/geometry/extensions/iterators/section_iterators.hpp
include/boost/geometry/extensions/nsphere/algorithms/disjoint.hpp
include/boost/geometry/extensions/nsphere/algorithms/within.hpp
include/boost/geometry/extensions/nsphere/strategies/cartesian/nsphere_in_box.hpp
include/boost/geometry/extensions/nsphere/strategies/cartesian/point_in_nsphere.hpp
include/boost/geometry/strategies/cartesian/box_in_box.hpp
include/boost/geometry/strategies/cartesian/point_in_box.hpp
include/boost/geometry/util/math.hpp
test/algorithms/relational_operations/covered_by.cpp
test/algorithms/relational_operations/disjoint/disjoint_point_box_geometry.cpp
test/algorithms/relational_operations/overlaps/overlaps_box.cpp
test/algorithms/relational_operations/touches/touches_box.cpp
test/algorithms/relational_operations/within/within.cpp
test/algorithms/set_operations/intersection/intersection.cpp

This PR reverts the changes done by PR https://github.com/boostorg/geometry/pull/318 and addresses the `sectionalize`/`partition` problem in a different way.
Spatial relations between Boxes and other Geometries must be checked as fast as possible (see the other PR for more info). This is why raw comparison operators gives the advantage here. Other Geometries are spatially-compared taking machine epsilon into account, so using functions like `math::equals()`. This is clearly an inconsistency, but I propose to keep it. Instead of making the checks consistent this PR enlarges the Boxes WRT epsilon in `sectionalize()` in a way that should be consistent with `math::equal()` checks performed for other Geometries.
I modified and used a function that was already there: `enlarge_sections()`. It …

Different approach for handling Boxes WRT machine epsilon

---

include/boost/geometry/algorithms/detail/is_valid/polygon.hpp

This is a follow up of PR #326 proposed by @jeremy-murphy.
The problem is that when `debug_print_complement_graph()` is called, `std::cout` needs to be defined
which requires the inclusion of `<iostream>` even in non-debug mode.
With this PR the call to `debug_print_complement_graph()` is guarded by the appropriate
macro and the use inclusion of `<iostream>` is no longer needed in non-debug mode.

Fix issue with use of std::cout only in debug mode

---

include/boost/geometry/algorithms/detail/distance/segment_to_box.hpp
test/algorithms/distance/distance_pointlike_linear.cpp

If there are NaN coordinates the assertions in distance(Pt, Box) cannot be reasonably checked, therefore this PR changes the conditions so if the original condition isn't met an additional check is performed if NaN coordinates were not involved. This is consistent with the general policy WRT invalid geometries, the algorithm doesn't fail but may generate invalid result.

Fix assertion failure in distance(Pt, Box) for NaN coordinates

---

include/boost/geometry/strategies/transform/inverse_transformer.hpp
include/boost/geometry/strategies/transform/matrix_transformers.hpp

This macro is also defined in boost/numeric/ublas/detail/config.hpp.
I assume that this is the behaviour you want, rather than checking the previous value?

[transform][strategies] Don't clobber BOOST_UBLAS_TYPE_CHECK macro.

---

include/boost/geometry/algorithms/detail/point_is_spike_or_equal.hpp
test/algorithms/is_valid.cpp

When checking whether a point `q` creates a spike or not with respect to two (ordered) points `a` and `b`, the first check performed is whether `q`, `a` and `b` are collinear. If so, then it is determined whether the vectors `q-b` and `b-a` have the same direction or not. For points with floating-point coordinates, due to rounding errors as well as due to the fact that equality to zero is checked using some tolerance, the three points may be detected as collinear. However, when the directions of the two vectors are checked, computations are done without taking into account any tolerance and this can lead to inconsistent results.
Here is one example geometry triggering this erroneous behavior: consider the polygon with WKT: `POLYGON((-200 0,-207.99999999999997 135,-208 1,-208 0,-208 …

Fix problem of numerical inconsistency when checking for spikes

---

include/boost/geometry/algorithms/detail/overlay/clip_linestring.hpp

I've noticed that `bg::intersection` fails to produce correct results when the input geometry and clipping box use integral types for coordinates.
The reduced testcase at https://github.com/springmeyer/boost-geometry-line-clipping-testcase/blob/master/bg-testcase.cpp produces this result with current boost geometry:
```
LINESTRING(-10 0,10 0)
LINESTRING(-20 0)
```
And produces the correct results (they should be the same) with the fix:
```
LINESTRING(-10 0,10 0)
LINESTRING(-10 0,10 0)
```
Per https://github.com/mapbox/mapnik-vector-tile/pull/102 I found and have been using a workaround for this problem: using `linear_ring` as the clipping shape which invokes a different code path entirely.
This is my first time contributing to `boost::geometry` so let me know if you'd like this report …

[algorithms][intersection] Fixes liang_barsky for integral data

---

include/boost/geometry/algorithms/detail/is_simple/areal.hpp
include/boost/geometry/algorithms/detail/is_simple/linear.hpp
include/boost/geometry/algorithms/detail/is_simple/multipoint.hpp
test/algorithms/is_simple.cpp

This PR addresses two Boost.Trac tickets: [11709](https://svn.boost.org/trac/boost/ticket/11709) and [11710](https://svn.boost.org/trac/boost/ticket/11710).
`bg::is_simple()` segfaults if given an empty linestring. In this PR the linestring is first checked for emptiness (before any further computations are performed) and `false` is returned is the linestring is found to be empty. Notice that the actual return value does not really matter, as empty linestrings are considered invalid, which means that the behavior of `bg::is_simple()` is undefined for them (the same holds actually for any BG algorithm operating on invalid input).
`bg::is_simple()` used to return `false` for empty multi-geometries. This was inconsistent with the behavior of `bg::is_valid()` which accepts empty …

Boost.Trac tickets 11709 and 11710

---

include/boost/geometry/algorithms/centroid.hpp
test/algorithms/centroid.cpp
test/algorithms/centroid_multi.cpp
test/algorithms/test_centroid.hpp

Fixes seg-faulting of centroid algorithm on multi-geometries when sub-geometry is empty. Test case is included.

[algorithms][centroid] Fix crash when multi-geometry contains empty geometry

---

include/boost/geometry/algorithms/detail/is_valid/box.hpp
include/boost/geometry/algorithms/detail/is_valid/has_invalid_coordinate.hpp
include/boost/geometry/algorithms/detail/is_valid/linear.hpp
include/boost/geometry/algorithms/detail/is_valid/pointlike.hpp
include/boost/geometry/algorithms/detail/is_valid/ring.hpp
include/boost/geometry/algorithms/detail/is_valid/segment.hpp
include/boost/geometry/algorithms/validity_failure_type.hpp
include/boost/geometry/policies/is_valid/failing_reason_policy.hpp
include/boost/geometry/util/has_infinite_coordinate.hpp
include/boost/geometry/util/has_nan_coordinate.hpp
include/boost/geometry/util/has_non_finite_coordinate.hpp
test/algorithms/is_valid.cpp

This PR partially addresses Boost.Trac ticket [11711](https://svn.boost.org/trac/boost/ticket/11711): "is_simple and is_valid - Points that are NaN or Infinity".
**Problem:** The problem with the existing `bg::is_valid()` implementation is that it may not handle properly geometries that have invalid floating-point coordinates, namely coordinates that are NaN or infinite. For such geometries `bg::is_valid()` may return `true`, which should not be the case.
**Fix:** In this PR the coordinates of a geometry whose coordinate type is a fundamental floating-point number are checked. If at least one coordinate is found to be NaN or infinite, the geometry is considered as invalid.
Note that for non-fundamental number types or fundamental non-floating-point types the check is essentially …

Boost.Trac ticket 11711

---

include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
test/algorithms/relational_operations/intersects/intersects_box_geometry.cpp

In a special case when the difference between points' coordinates of a Segment is 0 and the Segment is disjoint the functio returns wrong result. E.g. for:
SEGMENT(2 1 0,2 1 10)
BOX(0 0 0,10 0 10)
See also:
http://stackoverflow.com/questions/32457920/boost-rtree-of-box-gives-wrong-intersection-with-segment

Fix special case of intersects(Segment, Box)

---

include/boost/geometry/algorithms/detail/andoyer_inverse.hpp
include/boost/geometry/strategies/geographic/distance_andoyer.hpp
test/strategies/andoyer.cpp

This PR is related to #338
It fixes `andoyer_inverse` formula for points in antipodal areas. This formula can be used to calculate distances and azimuths between points using first order Andoyer-Lambert-Forsyth type approximation. Besides fixed distances the azimuths for points in the vincinity of antipodal point are convergent to the azimuth calculated for antipodal point.
This formula may be used in the Andoyer strategy which currently uses separate, older implementation.

Fix andoyer

---

include/boost/geometry/algorithms/buffer.hpp
include/boost/geometry/algorithms/convex_hull.hpp
include/boost/geometry/algorithms/detail/intersection/interface.hpp
include/boost/geometry/algorithms/difference.hpp
include/boost/geometry/algorithms/remove_spikes.hpp
include/boost/geometry/algorithms/simplify.hpp
include/boost/geometry/algorithms/sym_difference.hpp
include/boost/geometry/algorithms/transform.hpp
include/boost/geometry/algorithms/union.hpp
include/boost/geometry/util/range.hpp
test/util/range.cpp

This PR adds `range::back_insert_iterator` calling using Boost.Geometry version of push_back() specialized in traits and replaces the `std::back_inserter()` with `range::back_inserter()` in places where points are added to geometries.

Add range::back_inserter() and use it in algorithms when needed.

---

include/boost/geometry/io/svg/svg_mapper.hpp
include/boost/geometry/io/svg/write_svg.hpp
include/boost/geometry/io/svg/write_svg_multi.hpp
test/io/Jamfile.v2
test/io/svg/Jamfile.v2
test/io/svg/svg.cpp

SVG tag for Segment in `svg()` is `<line>`. This function is called by `svg_mapper`. The implementation of `svg_map` previously used only for Box is now used for Segment as well. Previously it was a separate implementation transforming Segments into Linestrings. This means that `svg_mapper` now outputs Segments as SVG Lines (`<line>`) instead of PolyLines (`<polyline>`).

[io] Support all geometries in svg() and use it in svg_mapper.

---

include/boost/geometry/policies/robustness/get_rescale_policy.hpp
test/algorithms/set_operations/intersection/intersection_aa_sph.cpp

This PR fixes the regression reported here:
https://svn.boost.org/trac/boost/ticket/11789
An assertion fails in `expand()` called from `sectionalize()` for non-cartesian geometries. It's because it is called for Points containing very big integral coordinates. The reason is that currently, by default, floating-point coordinates are rescaled into integral coordinates internally in set operations and these integral coordinates are passed into expand() to calculate bounding boxes. This also means that since these coordinates are normalized, the result is not correct. 
After merging this PR rescaling will be enabled only for geometries in cartesian CS.

Enable rescale policy only in cartesian coordinate system.

---

include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_original_visitor.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
include/boost/geometry/strategies/agnostic/point_in_poly_winding.hpp
test/algorithms/relational_operations/within/within_pointlike_geometry.cpp
test/strategies/winding.cpp

In spherical and geographic CS if a point has the same latitude as both points of a segment it doesn't mean that it lies on the segment. This PR fixes this case by scanning dimension 0 (X) instead of dimension 1 (Y). In spherical and geographic it's guaranteed that if longitude is the same a point lies on a segment.
Furthermore special checks are added for points lying on poles and segments going through poles.
IMPORTANT: The change of dimensions mentioned above influences buffer implementation which uses winding strategy directly and assume that this strategy scans in a specific dimension.

Fix winding strategy for spherical and geographic system.

---

include/boost/geometry/algorithms/detail/disjoint/box_box.hpp
include/boost/geometry/algorithms/detail/disjoint/point_box.hpp
include/boost/geometry/strategies/agnostic/point_in_box_by_side.hpp
include/boost/geometry/strategies/cartesian/box_in_box.hpp
include/boost/geometry/strategies/cartesian/point_in_box.hpp
include/boost/geometry/strategies/spherical/ssf.hpp
include/boost/geometry/util/normalize_spheroidal_coordinates.hpp
test/algorithms/relational_operations/Jamfile.v2
test/algorithms/relational_operations/covered_by_sph_geo.cpp
test/algorithms/relational_operations/intersects/Jamfile.v2
test/algorithms/relational_operations/intersects/intersects_sph_geo.cpp
test/algorithms/relational_operations/within/Jamfile.v2
test/algorithms/relational_operations/within/within.cpp
test/algorithms/relational_operations/within/within_sph_geo.cpp

This PR adds or changes the following:
- support spherical/geographic CS in `box_in_box` strategy and enable it as the default one
- support spherical/geographic CS in `point_in_box` strategy and enable it as the default one
- fix `disjoint()`/`intersects()` for point/box in spherical/geographic CS (using tools implemented for `point_in_box` strategy)
- fix `disjoint()`/`intersects()` for box/box in spherical/geographic CS (separate implementation)
This PR changes the way how `within(point, box)` and `covered_by(point, box)` is calculated by default. The reason is that a Box in spherical and geographical CS is not a Polygon. The differences are:
- the horizontal edge of a Box may be longer than 180 deg
- the horizontal edge of a Box is not defined by geodesic but by small circle …

Point/Box and Box/Box spatial relations in non-cartesian coordinate systems.

---

include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
include/boost/geometry/algorithms/detail/overlay/handle_touch.hpp

For all I know, some of these might even be real bugs...
But in any event, it's nice when Boost does not generate warnings for those of us who like to enable lots and lots of warnings.

Silence unused parameter warnings (GCC/Clang -Wextra).

---

include/boost/geometry/algorithms/detail/envelope/transform_units.hpp

As simple as it gets: remove semicolon after a function to silence GCC warnings (-Wpedantic)

Remove extraneous semicolon

---

include/boost/geometry/strategies/cartesian/cart_intersect.hpp
index/test/rtree/Jamfile.v2
index/test/rtree/rtree_intersects_geom.cpp
test/algorithms/relational_operations/intersects/intersects.cpp
test/algorithms/relational_operations/intersects/intersects_box_geometry.cpp
test/algorithms/relational_operations/intersects/intersects_multi.cpp
test/algorithms/relational_operations/within/within.cpp
test/algorithms/relational_operations/within/within_areal_areal.cpp
test/algorithms/relational_operations/within/within_linear_areal.cpp
test/algorithms/relational_operations/within/within_linear_linear.cpp

This fixes the ticket: https://svn.boost.org/trac/boost/ticket/12189
and issue reported in this thread: http://lists.boost.org/geometry/2016/05/3550.php
`relate_cartesian_segments::apply()` expects single `RobustPoint` type. This causes compilation error in e.g. relational operations when geometries using different point types are passed.

Fix/cart intersect for different RobustPoint types

---

include/boost/geometry/algorithms/detail/overlay/traversal_switch_detector.hpp

Introduced in f5b4e4a9fa0e491fea4644227f9e7499e0f8f36e
For a failing regression test take a look at [clang-linux-3.8~c++1z](http://www.boost.org/development/tests/develop/developer/output/teeks99-02-dc3-8-1z-Docker-64on64-boost-bin-v2-libs-geometry-test-algorithms-buffer-algorithms_buffer-test-clang-linux-3-8~c++1z-debug.html) for example.

Fix int vs. signed_size_type mismatch

---

include/boost/geometry/geometries/adapted/std_array.hpp
test/geometries/boost_array_as_point.cpp

Add point adaptor based on existing Boost.Array adaptor for C++11 std::array. I'm currently not very happy with the preprocessor checks in the test, but since the whole test is really small I think the preprocessor checks are not too bad. Anyway, I'm open to suggestions if changes are required.

Add C++11 std::array point adaptor

---

include/boost/geometry/io/wkt/read.hpp

Should presumably be 'too many tokens' rather than 'too much tokens'

Grammar fix

---

extensions/test/gis/io/wkb/read_wkb.cpp
extensions/test/gis/io/wkb/write_wkb.cpp
include/boost/geometry/algorithms/equals.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/ogc.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp
include/boost/geometry/extensions/gis/io/wkb/read_wkb.hpp
include/boost/geometry/extensions/multi/gis/io/wkb/detail/parser.hpp
include/boost/geometry/extensions/multi/gis/io/wkb/detail/writer.hpp
include/boost/geometry/extensions/multi/gis/io/wkb/read_wkb.hpp
include/boost/geometry/extensions/multi/gis/io/wkb/write_wkb.hpp

Adds support for Multi-geometries in the WKB data format.
This is the first draft, and a (better) version of the svn patches for Multi-geometry WKB support. I need help with the equals-algorithm used for the tests, as they currently only check the number of geometries (in the multi-geometry).
@mloskot

Support for reading and writing Multi-geometries

---

include/boost/geometry/algorithms/detail/buffer/get_piece_turns.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_original_visitor.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
include/boost/geometry/algorithms/detail/disjoint/multipoint_geometry.hpp
include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/overlay/pointlike_linear.hpp
include/boost/geometry/algorithms/detail/overlay/self_turn_points.hpp
include/boost/geometry/algorithms/detail/partition.hpp
test/algorithms/detail/partition.cpp

This PR makes partition() algorithm interruptable. The partition is interrupted when `visitor.apply(...)` returns `false`.
`self_ip_exception` is no longer needed, so removed. It's related to https://github.com/boostorg/geometry/pull/384
A side effect is performance increase. Below I show times gathered using this benchmark:
https://github.com/awulkiew/benchmark-geometry/blob/master/benchmarks/algorithms.cpp
data generated like this:
https://github.com/awulkiew/benchmark-geometry/blob/master/benchmarks/data.hpp
below:
- gcc is mingw-w64 4.9.1 -O2
- msvc is msvc-14 /O2
- develop - times for develop branch, interrupt - times for this branch
- relate-disj is relate() with disjoint mask
- zero - there is no overlap between geometries
- min - there is minimal overlap btween geometries …

Interruptable partition()

---

include/boost/geometry/algorithms/centroid.hpp
include/boost/geometry/algorithms/detail/has_self_intersections.hpp
include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info_la.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info_ll.hpp
include/boost/geometry/algorithms/detail/relate/result.hpp
include/boost/geometry/algorithms/detail/throw_on_empty_input.hpp
include/boost/geometry/io/wkt/read.hpp

BOOST_THROW_EXCEPTION was used before in the library to throw exceptions but not in all places. This PR adds it consistently in all cases besides one place being `self_section_visitor` defined in `algorithms/detail/overlay/self_turn_points.hpp`. It's because in this case the exception should be removed entirely. This requires the changes in `partition` which will be proposed in another PR.
Related ticket: https://svn.boost.org/trac/boost/ticket/12885

Throw exceptions using BOOST_THROW_EXCEPTION.

---

doc/index/make_qbk.py
doc/make_qbk.py

Delete Doxygen-generated files to avoid copying them into release archive.
Replace os.remove with shutil.rmtree to cope with sub-directories.
------
Boost 1.64.0 Beta1 source archive should not include  `html_by_doxygen` or `xml`.
It was discussed here http://lists.boost.org/geometry/2017/03/3618.php
I tried to follow Rene Rivera suggestions, http://lists.boost.org/Archives/boost/2017/03/233878.php, and regenerate release process to generate source archive w/o any Doxygen intermediate files generated in `libs/geometry/docs`. Hopefully, this will work for Rene.
If accepted and merged into `develop`, it should also be merged into `master` according to Rene's info http://lists.boost.org/Archives/boost/2017/03/233810.php
If there is anything I can do, let me know.

[doc] Add doxygen files clean-up if run with --release-build

---

include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/disjoint/multipoint_geometry.hpp
include/boost/geometry/algorithms/detail/is_valid/multipolygon.hpp
include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
include/boost/geometry/algorithms/detail/overlay/copy_segments.hpp
include/boost/geometry/algorithms/detail/overlay/follow.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
include/boost/geometry/algorithms/detail/overlay/overlay.hpp
include/boost/geometry/algorithms/detail/overlay/pointlike_linear.hpp
include/boost/geometry/algorithms/detail/overlay/range_in_geometry.hpp
include/boost/geometry/algorithms/detail/overlay/ring_properties.hpp
include/boost/geometry/algorithms/detail/overlay/select_rings.hpp
include/boost/geometry/algorithms/detail/overlay/self_turn_points.hpp
include/boost/geometry/algorithms/detail/point_on_border.hpp
include/boost/geometry/algorithms/detail/sections/sectionalize.hpp
include/boost/geometry/extensions/algorithms/detail/overlay/dissolver.hpp
include/boost/geometry/extensions/algorithms/dissolve.hpp
include/boost/geometry/strategies/agnostic/point_in_poly_winding.hpp
include/boost/geometry/strategies/cartesian/intersection.hpp
include/boost/geometry/strategies/cartesian/side_by_triangle.hpp
include/boost/geometry/strategies/geographic/intersection.hpp
include/boost/geometry/strategies/geographic/side.hpp
include/boost/geometry/strategies/spherical/intersection.hpp
include/boost/geometry/strategies/spherical/ssf.hpp
test/algorithms/overlay/overlay_cases.hpp
test/algorithms/overlay/select_rings.cpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/union/union.cpp

- add envelope and disjoint strategies getters into side, winding and intersection strategies
- pass envelope and disjoint strategies into sectionalize and/or partition in get_turns, disjoint, is_valid and overlay.
One more thing should be done, i.e. forcing `point_on_border` to return the vertex in at least non-cartesian coordinate systems. `point_on_surface` seems to be not used anywhere so there is no problem here. Do you have any thoughts regarding `point_on_border`? Second parameter `true` seems to be passed only in 2 places in the library, i.e. `overlay/intersection_insert.hpp` and `overlay/ring_properties.hpp`.

Use envelope-seg and disjoint-seg/box strategies in various algorithms.

---

include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp
include/boost/geometry/index/detail/rtree/node/weak_dynamic.hpp

addressof(*p) before construct() is not well-defined, since p does not alias storage that has an object constructed in it yet.

Use pointer_traits.to_address instead of addressof(*p)

---

include/boost/geometry/algorithms/detail/disjoint/box_box.hpp
test/algorithms/relational_operations/disjoint/disjoint_sph.cpp

This PR proposes a fix for the bug related to ticket https://svn.boost.org/trac10/ticket/13057
It is about producing wrong results when intersecting two linestrings with a common point.

Fix wrong results in intersection of linestrings with a common point

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp

The problem appears when side_calculator called from here: https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/algorithms/detail/overlay/get_turn_info_for_endpoint.hpp#L430 does not initialize the side strategy (i.e. inters.get_side_strategy()) passed as cont&. 
To fix this the PR proposes to remove const& from the declaration of m_side_strategy member.
Note that the issue is reported by using both gcc and clang (versions 4.8 and 3.4 respectively).

Fix problematic initialization of strategy passed as contant reference

---

include/boost/geometry/strategies/geographic/intersection.hpp
include/boost/geometry/strategies/spherical/intersection.hpp

This PR fixes the ticket: https://svn.boost.org/trac10/ticket/13035.
The problem is that near poles segments may be very short even though the longitudes of the endpoints are different. When the `equals(pt1, pt2)` is used to check if the segment is degenedated it may return false if longitudes are different but still near the pole the distance between the endpoints is close or equal to 0.
The spherical and geographic intersection strategies are modified in a way that distances between the segments are also taken into account when checking if a segment is degenerated to a point.

Handle degenerated segments near poles in spherical and geographic intersection strategies.

---

include/boost/geometry/algorithms/correct.hpp
include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/is_valid/ring.hpp
include/boost/geometry/algorithms/detail/multi_modify.hpp
include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
include/boost/geometry/algorithms/detail/overlay/overlay.hpp
include/boost/geometry/algorithms/detail/overlay/ring_properties.hpp
include/boost/geometry/algorithms/detail/overlay/select_rings.hpp
include/boost/geometry/extensions/algorithms/dissolve.hpp
test/algorithms/overlay/select_rings.cpp

The area strategy isn't propagated in all places where it should be, default strategy is used. This PR changes that.
It also adds strategy parameter to `correct()` algorithm allowing to pass area strategy.

Add missing propagation of area strategy in buffer, is_valid and overlay.

---

include/boost/geometry/strategies/geographic/area.hpp
test/algorithms/area/area_sph_geo.cpp

In this case `e2` is `0` which resulted in `c2` being `NaN` and at the end the final result being `NaN`. This PR sets `c2` to `a2` if `e2` is `0`.
Plus unnecessary `sqrt()` call is removed.

Fix geographic area strategy for sphere.

---

include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp

Found by Coverity:
"pointless_expression: The expression to_index1 >= 0 && to_index1 >=
0 does not accomplish anything because it evaluates to either of its
identical operands, to_index1 >= 0."

enrich_intersection_points: fix to_index0/to_index1 confusion

---

include/boost/geometry/algorithms/detail/intersection/multi.hpp
include/boost/geometry/algorithms/detail/overlay/follow.hpp
include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
test/algorithms/set_operations/difference/difference_areal_linear.cpp
test/algorithms/set_operations/intersection/intersection.cpp

This PR contains two fixes for the following bugs:
1. Regression in set operations caused by a different fix done in the past https://github.com/boostorg/geometry/pull/386 removing midpoint calculation. It manifests with 1.65 when both linestring's endpoints lie on a boundary but the interior of the linestring is in the exterior of polygon. In the following case the linestring is considered to be inside polygon so e.g. the result of difference(L, A, L) is empty:
2. Lack of intersection point if the first endpoint of a linestring lies on a boundary of polygon. E.g. in the following case the result of intersection(L, A, P) is empty:
Both bugs were fixed by using linear/areal turn operation, turn info policy and less function obejct for sorting turns (implemented for `relate`) in …

Fix L/A set operations

---

include/boost/geometry/algorithms/detail/sections/section_functions.hpp
test/algorithms/overlay/get_turns_areal_areal_sph.cpp
test/algorithms/set_operations/union/union.cpp

This is a fix for `get_turns`/`union` in geographic and spherical CS:
p1 = POLYGON((16 15,-132 10,-56 89,67 5,16 15))
p2 = POLYGON((101 49,12 40,-164 10,117 0,101 49))
The above case looks similar to this cartesian case:
p1 - red, p2 - green, north pole - blue
In this case for the second polygon very big section box is created and preceding/exceeding may return wrong result for such box. The result is only one intersection point detected in `get_turns`.

Fix preceding/exceeding in geographic CS

---

include/boost/geometry/algorithms/detail/overlay/add_rings.hpp
include/boost/geometry/algorithms/detail/overlay/overlay.hpp
test/algorithms/set_operations/union/Jamfile.v2
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_aa_geo.cpp

If the input non-cartesian geometries are valid the result of union may be too big, i.e. may have negative area or in other words is covering area greater than half of the globe. In such case currently `union_()` function returns empty result. This PR changes that, i.e. big geometry is returned.
Consider this case:
POLYGON((16 -15, -132 -22, -56 89, 67 -29, 16 -15))
+
POLYGON((101 49, 12 40, -164 -21, 117 -61, 101 49))
=
POLYGON((-128.119 74.498, -164 -21, 117 -61, 101 49, 65.345 54.723, 67 -29, 16 -15, -132 -22, -128.119 74.498))
with `(-128.119 74.498)` and `(65.345 54.723)` being 2 intersection points.
This PR is related to https://github.com/boostorg/geometry/pull/424. The case there is a smaller version of the one in this PR.
This PR removes positive area condition from `add_rings()` …

Fix for union in geographic CS not generating result if it's too big

---

include/boost/geometry/algorithms/detail/envelope/segment.hpp
include/boost/geometry/formulas/andoyer_inverse.hpp
include/boost/geometry/formulas/sjoberg_intersection.hpp
include/boost/geometry/formulas/thomas_direct.hpp
test/algorithms/envelope_expand/envelope_on_spheroid.cpp
test/algorithms/overlay/Jamfile.v2
test/algorithms/overlay/get_turns_linear_linear_geo.cpp
test/algorithms/overlay/test_get_turns.hpp
test/algorithms/set_operations/difference/difference_linear_linear.cpp
test/algorithms/set_operations/difference/test_difference_linear_linear.hpp
test/strategies/andoyer.cpp

This PR fixes handling of geometries containing segments having antipodal endpoints in particular with both endpoints at equator. It affects andoyer inverse, thomas direct and sjoberg intersection formulas as well as envelope algorithm.
Initially detected for `difference()` of these two geometries:
g1 = "LINESTRING(0 0, -3.14159265358979 0)"
g2 = "MULTILINESTRING((-2.1467549799530232 -0.12217304763960295,-2.5481807079117185 -0.90757121103705041,-2.6529004630313784 0.85521133347722067,0.92502450355699373 0.62831853071795796,-2.5307274153917754 0,2.8099800957108676 1.0646508437165401,-1.6057029118347816 -1.5009831567151219,0.2268928027592626 1.0646508437165401,-2.199114857512853 -0.017453292519943278,0 0.31415926535897898,0 0.57595865315812822,1.0471975511965967 …

Fix several algorithms for segments with antipodal endpoints.

---

include/boost/geometry/index/detail/rtree/node/scoped_deallocator.hpp
include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp
include/boost/geometry/index/detail/rtree/node/variant_static.hpp
include/boost/geometry/index/detail/rtree/node/weak_dynamic.hpp

Replace them by their cousins from std::allocator_traits.
Signed-off-by: Daniela Engert <dani@ngrt.de>

Most members of std::allocate are deprecated in C++17

---

example/c08_custom_non_std_example.cpp
example/with_external_libs/x04_wxwidgets_world_mapper.cpp
include/boost/geometry/extensions/iterators/circular_iterator.hpp
include/boost/geometry/extensions/iterators/segment_returning_iterator.hpp
include/boost/geometry/geometries/adapted/boost_polygon/hole_iterator.hpp
include/boost/geometry/index/inserter.hpp
include/boost/geometry/iterators/base.hpp
include/boost/geometry/iterators/closing_iterator.hpp
include/boost/geometry/iterators/concatenate_iterator.hpp
include/boost/geometry/iterators/detail/segment_iterator/range_segment_iterator.hpp
include/boost/geometry/iterators/ever_circling_iterator.hpp
include/boost/geometry/iterators/flatten_iterator.hpp
include/boost/geometry/util/range.hpp
include/boost/geometry/views/detail/boundary_view/implementation.hpp
include/boost/geometry/views/detail/points_view.hpp

Boost's iterator.hpp is deprecated (just like std::iterator in C++17). It does nothing but pulling std::iterator into namespace boost and including standard headers 'iterator' and 'cstddef'. Therefore get rid of including iterator.hpp (it had no effect in Boost.Geometry anyway) and replace inheritance by lifting std::iterator's members into the derived class. Instantiating std::iterator is granted with lengthy warning messages by latest MSVC when compiling in C++17 mode.
Signed-off-by: Daniela Engert <dani@ngrt.de>

Get rid of iterator.hpp

---

doc/reference/geometries/adapted/boost_array.qbk
doc/reference/geometries/adapted/boost_tuple.qbk

I think there is a full stop missing in the docs. That's all there is in this PR.

Typo: Add missing full stop to sentence

---

doc/doxy/Doxyfile
include/boost/geometry/strategies/spherical/area.hpp
include/boost/geometry/strategies/spherical/densify.hpp
include/boost/geometry/strategies/spherical/distance_haversine.hpp
include/boost/geometry/strategies/spherical/get_radius.hpp

For consistency with old spherical strategies and new geographic strategies allow specifying the type of member radius as either numeric radius type or sphere model. Make `double` the default radius type.

Support both RadiusType and Sphere as template parameter in spherial strategies.

---

doc/concept/point.qbk
doc/imports.qbk
doc/quickref.xml
doc/reference.qbk
doc/reference/geometries/adapted/std_array.qbk
doc/src/examples/geometries/adapted/Jamfile.v2
doc/src/examples/geometries/adapted/std_array.cpp

This adds the missing documentation for the `std::array` point adaptor added in #357. 
Copied the documentation entry and example from Boost.Array. Referred to `std::array` as "C++11 array container" throughout the text.
Link to new C++11 array container documentation page from
* reference
* quickref
* point concept
Generated the documentation locally and it seems everything was working fine.
* `std::array` needs C++11. Its example code is built successfully by the corresponding [Jamfile](https://github.com/boostorg/geometry/compare/develop...norbertwenzel:std-array-adaptor-docs?expand=1#diff-703795a7579032a7fd20c5ab34814bd0) only if compiled in C++11 mode or greater. I'm not sure if this causes any issues and/or if this can be worked around using `b2` (other than maybe explicitly adding …

Add C++11 std::array point adaptor docs

---

include/boost/geometry/algorithms/detail/relate/result.hpp

`geometry/algorithms/detail/relate/result.hpp` uses `memset` and `memcpy` but `cstring` is not included.

[srs] Add missing cstring include.

---

index/test/rtree/interprocess/Jamfile.v2
test/srs/projection_interface.cpp
test/srs/srs_transformer.cpp

Change \<host-os\> to \<target-os\>  in one Jamfile for cross-compilation.
And change <proj to fully qualified <boost::geometry::srs::par4::proj
to avoid confusing clang when compiling with the Dinkum STL
which has inline proj() in global namespace

Minor fixes for compilation with VxWorks 7

---

include/boost/geometry/algorithms/detail/assign_values.hpp
include/boost/geometry/algorithms/detail/envelope/box.hpp
include/boost/geometry/algorithms/detail/envelope/range_of_boxes.hpp
include/boost/geometry/algorithms/detail/expand/point.hpp
include/boost/geometry/util/is_inverse.hpp
include/boost/geometry/util/is_inverse_spheroidal_coordinates.hpp
test/algorithms/envelope_expand/expand_on_spheroid.cpp

This PR proposes a fix for issue https://github.com/boostorg/geometry/issues/498 by avoiding normalization for boxes created by ```make_inverse``` in spherical and geographic coordinate systems.

Fix make_inverse and expand issue 

---

test/iterators/segment_iterator.cpp

This fixes this memory leak:
```
=================================================================
==8204==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x101c3c592 in wrap__Znwm (/Users/danespringmeyer/projects/boost/libs/geometry/mason_packages/.link/lib/clang/5.0.1/lib/darwin/libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x63592)
#1 0x100c6127a in test_linestring_of_point_pointers::test_method() (/Users/danespringmeyer/projects/boost/libs/geometry/../../bin.v2/libs/geometry/test/iterators/iterators_segment_iterator.test/clang-darwin-5.0/debug/iterators_segment_iterator:x86_64+0x10022027a)
#2 0x100c5e802 in test_linestring_of_point_pointers_invoker() (/Users/danespringmeyer/projects/boost/libs/geometry/../../bin.v2/libs/geometry/test/ …
```

Avoid memory leak in segment_iterator.cpp test

---

include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp

An invalid polygon will trigger overflow when `previous_rank` is `0` as `previous_rank - 1` will overflow. This can be detected by passing an invalid polygon like `[[8128,3600],[8224,3664],[8128,3600]]` into `boost::geometry::intersection` and compiling with `-fsanitize=undefined`.
I'm aware that `boost::geometry::intersection` is not meant to be used with invalid polygons. However I still think that an overflow is not desirable. Better to prevent it or (if others think this fix is incorrect) perhaps an exception would be better?

Fix potential unsigned integer overflow in find_polygons_for_source

---

include/boost/geometry/algorithms/append.hpp

Solve problem described in #517

Avoid passing temporaries as function parameters when an L-value reference is expected

---

doc/make_qbk.py

Python 3 removed the global `execfile` function (see https://docs.python.org/3.5/whatsnew/3.0.html?highlight=execfile#builtins) and thus `make_qbk.py` script produces the error `name 'execfile' is not defined` (even with `Python 2.7.6` in my case).
This PR proposes a fix (tested with `Python 2.7.6` and `Python 3.4.3`).

Support python3 in building documentation

---

test/Jamfile.v2
test/self_contained_headers/Jamfile
test/self_contained_headers/main.cpp

Add Boost.Jam rule generating test target for each header found in specified location.
List test suites (target aliases) for groups of headers.
Build self_contained_headers test only if `CI` environment variable is NOT defined or on-demand, if `TEST_HEADERS` environment variable is defined, or if `b2 test/self_contained_headers` is requested from command line.
Related to issue #523
-----
First, this PR does not attempt to fix any headers, not yet.
I've run all the headers tests on 24 CPUs (48 logical cores) as follows:
```shell
cd libs/geometry
b2 -j 16 test/self_contained_headers >build.log 2>&1
```
AFAICT, it compile-tests *~900* headers in less than *4 minutes*:
```shell
cat build.log | grep -E -o "c\+\+.+\~hpp\.test" | sort | uniq | wc -l
898
cat build.log | grep -E -o …
```

Add compile-only tests verifying headers are self-contained

---

test/Jamfile.v2

Disable headers tests on CI services and during regression tests.
Refines #525

Run headers tests only on demand

---

doc/doxy/Doxyfile
doc/doxy/doxygen_input/groups/groups.hpp
doc/html/index.html
doc/make_qbk.py
doc/reference.qbk
doc/release_notes.qbk
include/boost/geometry/algorithms/detail/distance/interface.hpp
include/boost/geometry/algorithms/discrete_frechet_distance.hpp
include/boost/geometry/algorithms/discrete_hausdorff_distance.hpp
include/boost/geometry/io/dsv/write.hpp

1. Wrong arguments' names of `discrete_hausdorff_distance()`
2. Wrong description of `distance()`
https://github.com/boostorg/geometry/issues/521
3. Missing documentation of `dsv()`
https://github.com/boostorg/geometry/issues/520

Documentation fixes.

---

include/boost/geometry/core/config.hpp
include/boost/geometry/srs/projections/impl/dms_parser.hpp
include/boost/geometry/srs/projections/par_data.hpp

This is a workaround for the following error:
boost/geometry/srs/projections/par_data.hpp(92) : error C2536: 'boost::geometry::srs::detail::towgs84<T>::boost::geometry::srs::detail::towgs84<T>::m_data' : cannot specify explicit initializer for arrays
I added `core/config.hpp` file allowing us to add defines conveniently.

Add workaround for msvc-12 faulty array initialization.

---

include/boost/geometry/algorithms/detail/relate/turns.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/union/union_multi.cpp

With this PR I intend to fix or suppress test failures in set operations.
There are several cases failing right now. Most of them are failing correctly due to a bug in `sym_difference()`: https://github.com/boostorg/geometry/issues/515 and became visible because of this change: https://github.com/boostorg/geometry/pull/533.
There is a test case which is different, i.e. `difference()` case `mysql_23023665_6`:
red: `POLYGON((6 7,18 14, -8 1, 0 0, 18 -8, 6 7), (6 0, -4 3, 5 3, 6 0))`
green: `POLYGON((2 3,-3 5,-10 -1,2 3))`
blue: `difference(green, red);`
This case is fixed by the first commit in this PR which changes the `relate()` algorithm to use rescaling just like set operations. In other words to use it for areal geometries. This make `relate()` just slightly more consistent with set …

Fix or suppress validity test failures in set operations

---

doc/release_notes.qbk
include/boost/geometry/strategies/geographic/distance_cross_track.hpp
test/algorithms/distance/distance_geo_pl_l.cpp

caused by out of bounds argument in `acos` function

Fix nan result in geo distance

---

include/boost/geometry/formulas/interpolate_point_spherical.hpp

interpolate_point_spherical: inline var initialization

---

include/boost/geometry/algorithms/detail/disjoint/areal_areal.hpp
include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
include/boost/geometry/strategies/cartesian/intersection.hpp
include/boost/geometry/strategies/geographic/intersection.hpp
include/boost/geometry/strategies/spherical/intersection.hpp
test/algorithms/disjoint/disjoint_seg_box.cpp
test/algorithms/disjoint/disjoint_sph.cpp

This fixes issues https://github.com/boostorg/geometry/issues/466 and https://github.com/boostorg/geometry/issues/579. The latter is fixed by commenting out the `alp1` parameter so it's similar to the proposed fix https://github.com/boostorg/geometry/pull/580 but here the code is not removed in case we decided to keep the parameter. I'm fine with removing it entirely so merging both PRs.

Fix disjoint Box/Poly and Box/Seg

---

doc/doxy/Doxyfile

I'm sorry for the timing of this rather hastily put together pull request, however, I just now noticed that the documentation pages for covered_by, intersects, overlaps and touches are empty (since 1.65, in 1.64 they still had content) in the online documentation and the next release is already in the release candidate phase.
See https://www.boost.org/doc/libs/1_70_0_beta1/libs/geometry/doc/html/geometry/reference/algorithms/touches.html for example.
The result of this change is that some content shows up in the corresponding generated qbk files for these 4 algorithms which was not the case without the change (they had just 15 lines but no actual content), I'm not sure, though, whether this already fixes the issue. But with the release being so close I thought it might be more helpful to …

Fix: Add headers for touches, covered_by, intersects, overlaps to doc

---

extensions/test/algorithms/Jamfile.v2
extensions/test/gis/latlong/Jamfile.v2

There are tests in extensions that use old code and does not compile or fail. I propose to deactivate for now and in the future fix them (if  they are relevant) or remove them.

Deactivate old tests that fail or not compile in extensions

---

include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
test/algorithms/set_operations/union/union.cpp

Closer point to measure distance, which makes that measurement more precise.

[TURNS] Disable start-turns, and take the closer point 

---

include/boost/geometry/srs/projections/proj/cea.hpp

Currently the code does not compile if `T` is different than `double`.

Fix call to pj_qsfn in cea

---

include/boost/geometry/formulas/differential_quantities.hpp
include/boost/geometry/formulas/thomas_direct.hpp
include/boost/geometry/strategies/geographic/buffer_point_circle.hpp

This PR also adds asserts in formulas.
It addresses the issue: https://github.com/boostorg/geometry/issues/542
It also fixed some failing cases for me from algorithms_buffer_point_geo test file (tested only with msvc-14.1).

Fix azimuth validity in geographic_point_circle buffer strategy.

---

include/boost/geometry/algorithms/detail/buffer/line_line_intersection.hpp
test/algorithms/buffer/buffer_linestring.cpp

now using general form (which will be used later more widely). This fixes
some numerical issues.
Including testcase, reported as #596

Fix of issue #596 - [buffer] fix line/line intersection point calculation for some cases,

---

include/boost/geometry/strategies/transform/matrix_transformers.hpp

The example file 06_b_transformation_example contains this useful example for composing matrix_transformers
`matrix_transformer<double, 2, 2> combined(rotate.matrix() * translate.matrix());`.
The analogue of this for matrix_transformer<CalculationType, 3, 3> causes a compiler error because the corresponding constructor is missing in the 3d case. This pull request is designed to fix this by adding the constructor 
`    inline matrix_transformer(matrix_type const& matrix)
: m_matrix(matrix)
{}`
to matrix_transformer<CalculationType, 3, 3>.

Add a constructor that takes matrix_type to matrix_transformer<CalculationType, 3, 3>

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/index/detail/algorithms/intersection_content.hpp
include/boost/geometry/index/parameters.hpp

Remove unused parameters in some algorithms to avoid compilation warnings.

Remove unused parameters

---

include/boost/geometry/algorithms/detail/calculate_point_order.hpp
include/boost/geometry/algorithms/remove_spikes.hpp
include/boost/geometry/strategies/cartesian/point_order.hpp
include/boost/geometry/strategies/geographic/point_order.hpp
include/boost/geometry/strategies/point_order.hpp
include/boost/geometry/strategies/spherical/point_order.hpp
test/algorithms/detail/Jamfile.v2
test/algorithms/detail/calculate_point_order.cpp

This solves the issue caused by inaccurate area calculation for small polygons with andoyer formula.
For geographic CS instead of area the sum of external angles is calculated.
I tried something new with this algorithm. Instead of being dispatched by geometry tag I dispatched it by strategy's `version_tag`.
There are 2 versions of this algorithm:
- area-based which simply calculates the area and checks its value
- azimuth-based which filters out point duplicates and spikes (it's modified version of `remove_spikes`)
The version of an algorithm is defined by the strategy as a member type `version_tag`. The reason for this is that both algorithms are very different and the alternative would be to implement everything in strategies.
This algorithm works for Rings only (actually Ranges of …

Add new algorithm detail::calculate_point_order() with strategies (and optimize remove_spikes()).

---

include/boost/geometry/algorithms/for_each.hpp
test/algorithms/for_each.cpp

Added test to verifying the fix.
Fixes #624
----
The added tests can reproduce the bug in the current `for_each_segment` implementation without the proposed fix:
```console
bionic:/mnt/d/boost.wsl/libs/geometry/test/algorithms$ g++  -std=gnu++2a -fvisibility-inlines-hidden -fPIC -m64 -pthread -O0 -fno-inline -Wall -g -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DBOOST_NO_AUTO_PTR -I".." -I"../../../.." -I"../../../../boost/geometry/extensions/contrib/ttmath" -c -o "../../../../bin.v2/libs/geometry/test/algorithms/algorithms_for_each.test/gcc-7/debug/threading-multi/visibility-hidden/for_each.o" "for_each.cpp" && g++   -std=gnu++2a -o "../../../../bin.v2/libs/geometry/test/algorithms/algorithms_for_each.test/gcc-7/debug/threading-multi/visibility-hidden/algorithms_for_each" -Wl,--start-group …
```

[for_each] Fix for_each_segment to avoid incrementing iterator over empty range

---

include/boost/geometry/algorithms/detail/equals/implementation.hpp
include/boost/geometry/algorithms/detail/equals/interface.hpp
include/boost/geometry/algorithms/detail/relate/de9im.hpp
include/boost/geometry/algorithms/detail/relate/relate_impl.hpp
include/boost/geometry/algorithms/detail/relate/result.hpp
include/boost/geometry/algorithms/detail/touches/implementation.hpp

The purpose is to simplify writing generic code with relational operations. Consider e.g.:
bg::equals(linestring, polygon);
bg::touches(point, linestring);
bg::crosses(point, linestring);
bg::overlaps(point, linestring);
before: compilation error,
this PR: compiles and always returns `false`.

Implement relops for arguments always resulting in false.

---

include/boost/geometry/algorithms/detail/overlay/follow.hpp
include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
include/boost/geometry/algorithms/detail/relate/linear_linear.hpp
include/boost/geometry/algorithms/detail/relate/turns.hpp
test/algorithms/set_operations/difference/Jamfile.v2
test/algorithms/set_operations/difference/difference_l_a_sph.cpp
test/to_svg.hpp

This is a fix for issue https://github.com/boostorg/geometry/issues/619
Currently only fractions are used to check if points are equal in `relate::turns::less` predicate passed to `std::sort` to sort turns before analysis in relops and setops. This may give wrong results in some cases.

While sorting turns in relops and setops compare also point coordinates.

---

include/boost/geometry/strategies/geographic/parameters.hpp
include/boost/geometry/strategies/strategies.hpp

The reasons are:
- karney formulas expect degrees so they won't work with strategies right now
- `karney_inverse` requires C++11 (and doesn't compile with older VS because of min/max macros)
Regarding the second bullet, see: https://www.boost.org/development/tests/develop/developer/geometry.html
If this PR is merged the formulas will be reincluded when https://github.com/boostorg/geometry/issues/635 is addressed and the inverse formula is either adapted to C++03 or the standard required by the library is bumped to C++11.

[strategies] Do not include karney strategy and parameters by default.

---

include/boost/geometry/formulas/karney_inverse.hpp
include/boost/geometry/util/series_expansion.hpp
test/formulas/Jamfile.v2
test/formulas/inverse_karney.cpp

Plus warning fix.
Even though this formula requires C++11 and is no longer included by default (see https://github.com/boostorg/geometry/pull/636) it is still tested (in `test/formulas/inverse.cpp`). Without this fix it does not compile with MSVC even when C++11 is supported.

Fix MSVC compailation errors in karney_inverse.

---

extensions/test/gis/io/wkb/read_wkb.cpp
extensions/test/gis/io/wkb/write_wkb.cpp
extensions/test/index/rtree.cpp
test/geometry_test_common.hpp
test/io/wkt/wkt_multi.cpp

Fixing warning `This header is deprecated. Please use <boost/test/tools/floating_point_comparison.hpp> instead.`

Fix deprecated header for floating_point_comparison

---

include/boost/geometry/formulas/karney_inverse.hpp

Using static const variables instead of static constexpr variables also
enables the use of user-defined types without constexpr constructor.
My hope is to fix linking errors recently detected at CircleCI [1] after https://github.com/boostorg/geometry/pull/644 was merged, e.g.:
boost/geometry/formulas/karney_inverse.hpp:182: undefined reference to `boost::geometry::formula::karney_inverse<double, true, true, true, true, true, 8ul>::c90'
[1] https://circleci.com/gh/boostorg/geometry/6716

Fix odr-used constants and improve const-correctness in karney_inverse.

---

include/boost/geometry/index/detail/rtree/linear/redistribute_elements.hpp
include/boost/geometry/index/detail/rtree/node/node.hpp
include/boost/geometry/index/detail/rtree/node/subtree_destroyer.hpp
include/boost/geometry/index/detail/rtree/pack_create.hpp
include/boost/geometry/index/detail/rtree/quadratic/redistribute_elements.hpp
include/boost/geometry/index/detail/rtree/query_iterators.hpp
include/boost/geometry/index/detail/rtree/rstar/choose_next_node.hpp
include/boost/geometry/index/detail/rtree/rstar/insert.hpp
include/boost/geometry/index/detail/rtree/rstar/redistribute_elements.hpp
include/boost/geometry/index/detail/rtree/utilities/are_boxes_ok.hpp
include/boost/geometry/index/detail/rtree/utilities/are_counts_ok.hpp
include/boost/geometry/index/detail/rtree/utilities/are_levels_ok.hpp
include/boost/geometry/index/detail/rtree/utilities/gl_draw.hpp
include/boost/geometry/index/detail/rtree/utilities/print.hpp
include/boost/geometry/index/detail/rtree/utilities/statistics.hpp
include/boost/geometry/index/detail/rtree/utilities/view.hpp
include/boost/geometry/index/detail/rtree/visitors/children_box.hpp
include/boost/geometry/index/detail/rtree/visitors/copy.hpp
include/boost/geometry/index/detail/rtree/visitors/count.hpp
include/boost/geometry/index/detail/rtree/visitors/destroy.hpp
include/boost/geometry/index/detail/rtree/visitors/distance_query.hpp
include/boost/geometry/index/detail/rtree/visitors/insert.hpp
include/boost/geometry/index/detail/rtree/visitors/is_leaf.hpp
include/boost/geometry/index/detail/rtree/visitors/remove.hpp
include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
include/boost/geometry/index/detail/serialization.hpp
include/boost/geometry/index/rtree.hpp
index/test/rtree/exceptions/test_exceptions.hpp
index/test/rtree/test_rtree.hpp

- improve readability/maintainability of the code by replacing lists of types in visitors with one type of `MembersHolder` and getting all needed types from it.
- improve exception safety by removing exceeding element if there are too many elements in a node after exception is thrown in `split`, so even if a user chooses to try to insert something into the rtree, even though the state of the rtree is not valid the new element won't be put out of bounds which now would result in assert or segfault. (I consider it a bug).

R-tree improvements.

---

doc/reference/geometries/point_xy.qbk

Documentation page of [point_xy](https://www.boost.org/doc/libs/1_72_0/libs/geometry/doc/html/geometry/reference/models/model_d2_point_xy.html) has same note written twice, so I removed one.

Deleted extra note in point_xy documentation

---

.github/workflows/minimal-clang.yml
.github/workflows/minimal-gcc.yml
.github/workflows/minimal-msvc.yml

This is to enable a minimal CI check for the pull requests, to assist
contributors and reviewers, as well as for direct commits and merges.
For each toolset, this runs permutation of `b2 cxxstd=03,11,14,17,2a variant=debug,release address-model=32,64`, with `cxxstd` list tailored according to the actual toolset.
------
The CI for pull requests was discussed in https://lists.boost.org/geometry/2020/03/3791.php

Add GitHub Actions to build test//minimal with Clang, GCC, MSVC

---

test/geometries/Jamfile
test/geometries/linestring.cpp
test/geometries/multi_linestring.cpp
test/geometries/multi_point.cpp
test/geometries/multi_polygon.cpp
test/geometries/point.cpp
test/geometries/point_xy.cpp
test/geometries/point_xyz.cpp
test/geometries/polygon.cpp
test/geometries/ring.cpp

This PR is meant to fix #673. I have added unit tests for all the geometry models. Test includes working of default and copy constructors, assignment operator and custom test using `std::initializer_list`. I have covered tests for all the coordinate systems. I have tested all the files locally using GCC 7.4.

Adding missing unit tests for geometry models

---

extensions/test/headers/Jamfile
include/boost/geometry/extensions/triangulation/strategies/cartesian/detail/precise_math.hpp

I noticed these two missing includes when I tried to use the header on its own.

Add missing headers to precise_math.hpp

---

README.md
doc/compiling.qbk
include/boost/geometry/geometry.hpp

Following discussion in #590, we are identifying support for C++03
as a candidate for removal from future releases of Boost.Geometry.
Issue [deprecation](http://eel.is/c++draft/depr#2) warning during compilation in C++03 conformance mode
Users can define BOOST_GEOMETRY_DISABLE_DEPRECATED_03_WARNING to disable it.

Deprecate C++03 in Boost 1.73 as preparation for C+14 switch

---

include/boost/geometry/extensions/triangulation/strategies/cartesian/detail/precise_math.hpp
include/boost/geometry/extensions/triangulation/strategies/cartesian/side_robust.hpp

Hello,
this PR contains some changes for implementation details of side_robust that (on my machine, for the benchmarks that can be found in https://github.com/boostorg/geometry/issues/699#issuecomment-617775379 ) lead to a speedup of ~x1.5 with GCC and ~x4 with Clang in the execution of side_robust::apply for completely random input and a more moderate speedup for degenerate input. Correctness has been verified using the tests linked in the opening post found in https://github.com/boostorg/geometry/issues/699 .

Performance improvements for side_robust

---

include/boost/geometry/algorithms/detail/intersection/areal_areal.hpp
include/boost/geometry/algorithms/detail/intersection/multi.hpp
include/boost/geometry/algorithms/detail/overlay/intersection_insert.hpp
include/boost/geometry/algorithms/detail/tupled_output.hpp
include/boost/geometry/algorithms/difference.hpp
include/boost/geometry/algorithms/sym_difference.hpp
include/boost/geometry/algorithms/union.hpp
test/algorithms/set_operations/difference/Jamfile
test/algorithms/set_operations/difference/difference_tupled.cpp
test/algorithms/set_operations/sym_difference/Jamfile
test/algorithms/set_operations/sym_difference/sym_difference_tupled.cpp
test/algorithms/set_operations/union/Jamfile
test/algorithms/set_operations/union/union_tupled.cpp

This is a followup PR after https://github.com/boostorg/geometry/pull/650
It adds support for tupled-output in the rest of set operations. The interface is the same for all of them and allows the user to use the same output type. Here is an example:
```
polygon po1, po2;
bg::read_wkt("POLYGON((0 0, 0 5, 5 5, 5 0, 0 0))", po1);
bg::read_wkt("POLYGON((0 0, 0 1, 6 1, 5 2, 5 5, 5 6, 4 5, 4 7, 7 7, 7 0, 0 0))", po2);
bg::correct(po1);
bg::correct(po2);
std::tuple<multi_point, multi_linestring, multi_polygon> d, i, sd, u;
bg::difference(po1, po2, d);
bg::intersection(po1, po2, i);
bg::sym_difference(po1, po2, sd);
bg::union_(po1, po2, u);
auto print_result = [&](char op, auto const& res) {
std::cout << bg::wkt(po1) << ' ' << op << ' ' << bg::wkt(po2) << '\n'
<< bg::wkt(std::get<0>(res)) << '\n' …
```

Support tupled-output in difference, sym_difference and union_.

---

doc/geometry.qbk
include/boost/geometry/index/detail/rtree/pack_create.hpp
include/boost/geometry/index/rtree.hpp

As discussed in #718, it's not currently possible to specify an allocator for the packing process used during the construction of the r-rtee. This is desirable in some situations when dealing with constrained memory systems.
This PR adds overloads for both `bgi::detail::index::rtree::pack` and `bgi::rtree` classes to support the aforementioned allocator without interfering with the existing interfaces.

Add custom pack allocator to r-tree constructor

---

include/boost/geometry/algorithms/detail/overlay/follow.hpp
include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp

Fixes #727 
-----
MWE that triggers the warning
```cpp
#include <deque>
#include <boost/geometry.hpp>
namespace bg = boost::geometry;
int main()
{
using line_t = bg::model::linestring<bg::model::d2::point_xy<double>>;
line_t green, blue;
bg::read_wkt("LINESTRING(0 0, 2 0)", green);
bg::read_wkt("LINESTRING(-1 -1, -1 2)", blue);
std::deque<line_t> output;
bg::union_(green, blue, output);
bg::intersection(green, blue, output);
}
```
------
It's worth to be aware usage of the macro
https://github.com/boostorg/geometry/blob/cff2ee9d6c30afba4fe6cf64b3d65080372f8a5d/include/boost/geometry/util/condition.hpp#L35
may trigger the MSVC [code analysis warning C6319](https://docs.microsoft.com/en-us/cpp/code-quality/c6319).

Fix MSVC warning C4127: conditional expression is constant

---

include/boost/geometry/strategies/cartesian/intersection.hpp

This is to avoid using both non-rescaled and rescaled coordinates in one method.
It is completely independent of the other PR created today, and should result in no failures

[intersection] refactor segment-intersection class

---

test/algorithms/buffer/buffer_countries.cpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_linestring.cpp
test/algorithms/buffer/buffer_multi_point.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/buffer/buffer_point.cpp
test/algorithms/buffer/buffer_polygon.cpp
test/algorithms/buffer/test_buffer.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/difference/difference_multi_spike.cpp
test/algorithms/set_operations/difference/test_difference.hpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/intersection/intersection_multi.cpp
test/algorithms/set_operations/intersection/test_intersection.hpp
test/algorithms/set_operations/union/test_union.hpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp
test/count_set.hpp
test/geometry_test_common.hpp

- some cases are fixed in the meantime, this is updated
- in `difference` there might be slivers which are still OK, therefore an `count_set` is used there
- when `BOOST_GEOMETRY_TEST_FAILURES` is defined, it also writes expected failures - this makes it much easier to detect improvements (or regressions)
- this also shows insight in the current state, which is more or less in par with the rescaling - this means we might switch in next release (and one or two releases later remove the rescaling code)

[test] update testsuite

---

include/boost/geometry/algorithms/detail/distance/default_strategies.hpp

This PR fixes an issue on default strategy selection for distance algorithm and affects all coordinate systems. 
The default strategy for the cases `polygonal/box` and `linear/box` should be a segment/box strategy and not a point/segment one.

Add missing cases for default strategies in distance algorithm

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/strategies/cartesian/intersection.hpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/union/union.cpp

* in intersection a check is made for overlap (solving some errors mainly in small scale AND nearly collinear situations)
* in touch a special case is added where intersection reports touching segments, but they are just not touching
* in touch some sides were reported as 0 while, in FP, they are distinguishable and that can be used to fix some errors

Fix errors in some floating point cases

---

include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
include/boost/geometry/algorithms/detail/disjoint/linear_segment_or_box.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/for_each.hpp
include/boost/geometry/strategies/geographic/intersection.hpp
include/boost/geometry/strategies/intersection_strategies.hpp

A fix for https://github.com/boostorg/geometry/issues/716
It also removes some unneeded typedefs.

Fix dangling references for referring_segment and proxy references returned by iterators.

---

.github/workflows/minimal-clang.yml
.github/workflows/minimal-gcc.yml
include/boost/geometry/arithmetic/cross_product.hpp
include/boost/geometry/arithmetic/dot_product.hpp
include/boost/geometry/core/access.hpp
include/boost/geometry/core/coordinate_dimension.hpp
include/boost/geometry/geometries/box.hpp
include/boost/geometry/geometries/point.hpp
include/boost/geometry/geometries/point_xy.hpp
include/boost/geometry/geometries/point_xyz.hpp
include/boost/geometry/geometries/segment.hpp

I was playing with `constexpr`. This PR allows to do something like this:
```
using point = bg::model::point<double, 2, bg::cs::cartesian>;
using point_xy = bg::model::d2::point_xy<double>;
using point_xyz = bg::model::d3::point_xyz<double>;
using box = bg::model::box<point>;
using segment = bg::model::segment<point>;
constexpr point p0 = point{};
constexpr point p1 = point{ 1 };
constexpr point_xy p2 = point_xy{ 1, 2 };
constexpr point_xyz p3 = point_xyz{ 1, 2, 3 };
constexpr double d0 = bg::get<0>(p0);
constexpr double d1 = bg::get<0>(p1);
constexpr double d2 = bg::get<1>(p2);
constexpr double d3 = bg::get<2>(p3);
constexpr double d12 = bg::dot_product(p1, p2);
constexpr point_xyz p33 = bg::cross_product(p3, p3);
constexpr box b = box{ p0, p1 };
constexpr double d4 = bg::get<0, 0>(b); …
```

Support constexpr in points, segment, box, get, dot and cross products.

---

.github/workflows/minimal-clang.yml
.github/workflows/minimal-gcc.yml
include/boost/geometry/algorithms/convert.hpp
include/boost/geometry/algorithms/detail/disjoint/areal_areal.hpp
include/boost/geometry/algorithms/detail/for_each_range.hpp
include/boost/geometry/algorithms/detail/touches/implementation.hpp
include/boost/geometry/algorithms/for_each.hpp
include/boost/geometry/strategies/agnostic/hull_graham_andrew.hpp
test/algorithms/for_each.cpp
test/algorithms/touches/touches.cpp

I was playing with for_each family of functions and C++14. With the newer standard we can greatly simplify some parts of the code applying some Actor/Policy to Points/Segments/Ranges or checking some predicate for them.
Let me know what you think.
Changes summary:
`for_each_range` now expects functors instead of structs with `apply()` member function.
`for_each_segment` now calls functor also for degenerated ranges for consistency with `segment_iterator`.
New algorithms based on `std::all_of`, `std::any_of` and `std::none_of`
- `all_points_of`, `any_point_of`, `none_point_of`
- `all_segments_of`, `any_segment_of`, `none_segment_of`
- `all_ranges_of`, `any_range_of`, `none_range_of`
New algorithms used in several places in the library.

Refactor for_each_x and implement new algorithms.

---

doc/concept/point.qbk

This is the documentation I found to be missing. I posted something like it at https://stackoverflow.com/a/62777496/874660 but switched this example to `std::array<T,N>` to be more standard.

Add example showing how std::array<T, N> can model the Point concept

---

include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/buffer/get_piece_turns.hpp
include/boost/geometry/algorithms/detail/buffer/line_line_intersection.hpp
include/boost/geometry/algorithms/detail/sections/section_functions.hpp
include/boost/geometry/strategies/cartesian/buffer_point_square.hpp
include/boost/geometry/strategies/cartesian/turn_in_ring_winding.hpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_linestring.cpp
test/algorithms/buffer/buffer_multi_point.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/buffer/buffer_point.cpp
test/algorithms/buffer/buffer_polygon.cpp
test/algorithms/buffer/test_buffer.hpp
test/algorithms/buffer/test_buffer_svg.hpp
test/string_from_type.hpp

This should (at least partly) fix the recent observation of @awulkiew , and contains parts of my work I did before to support types other than double (without rescaling)

[buffer] Several changes necessary to handle different types

---

include/boost/geometry/algorithms/area_result.hpp

Visual Studio 2015 C++14 (Default) we encountered C2146  stating
`error C2146: syntax error: missing ',' before identifier 'result_type'`
reference: 
https://ci.appveyor.com/project/lpranam/astronomy-il73i/branch/develop/job/uo7pirc0s4v9xpb2

resolve c2146 on vs15 with area_result declaration

---

test/algorithms/buffer/buffer_countries.cpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_linestring.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/buffer/buffer_polygon.cpp
test/algorithms/buffer/test_buffer.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/difference/test_difference.hpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/intersection/intersection_multi.cpp
test/algorithms/set_operations/intersection/test_intersection.hpp
test/algorithms/set_operations/union/test_union.hpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp
test/count_set.hpp
test/expectation_limits.hpp
test/geometry_test_common.hpp

I was already busy with this before the rework on buffer.
This is preparing a next commit and avoiding many ifdefs for situations which are OK (just for float a bit more slack, or for more precise types a different amount of output rings or small slivers.
Also you can see the state - often without rescaling tests perform better than with. But I still have to verify all robustness tests too, and there is a PR in preparation to include start turns, which can be necessary in some cases (if rescaling if removed)

Conform the countset, replace many #ifdefs with expectation limits

---

include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp

tried to parse a spatialite WKB blob with this code but the byte_order byte was replaced by a '69' token :
parsing this byte is successful but if the value read is not part of the enum, the function returns true but the order parameter is left untouched. 
Calls to that function elsewhere in the code do not initialise the order parameter.
see https://github.com/boostorg/geometry/blob/869e72fc01f2fce5ec3bcdfb91afab65ebd3ec6f/include/boost/geometry/extensions/multi/gis/io/wkb/detail/parser.hpp#L83
another option would be to return false in that case, but it didn't fit my need

fixed risk of undefined behavior when parsing a byte_order byte

---

include/boost/geometry/algorithms/area_result.hpp
include/boost/geometry/arithmetic/cross_product.hpp
include/boost/geometry/arithmetic/dot_product.hpp
include/boost/geometry/geometries/point.hpp
include/boost/geometry/strategies/comparable_distance_result.hpp
include/boost/geometry/strategies/default_length_result.hpp
include/boost/geometry/strategies/distance_result.hpp

If you see our regression tests it looks like the majority of them compiles with VS2015:
https://www.boost.org/development/tests/develop/developer/geometry.html
Therefore I checked how much effort would it take to make all of them to compile. It seems that it was not much. VS2015 doesn't have full `constexpr` support and `boost::variant`'s is implemented using dummy template parameters instead of parameter pack.
For `constexpr` it was sufficient to disable it in some places and add explicitly initialize class member in other.
In order to analyze types of `boost::variant` I decided to not use Boost.MPL as it was before but instead to check raw template parameters, i.e. to check if they are geometries or not. This works for both dummy parameters and types that are not geometries. And while …

Add constexpr and boost::variant workarounds for vs2015.

---

include/boost/geometry/algorithms/detail/overlay/debug_turn_info.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp

This happens in rare cases. When they arrive there (or leave), their fraction should be 1 (or 0). The fraction is calculated and is sometimes nearly 1 (or ), but not considered so.
This can be fixed without any threshold because the information on arrival is already there.
It fixes ~10% of the remaining errors in the `recursive_polygons_buffer` test.
Several cases (added last PR) are fixed now. And I added 3 new cases (not yet fixed by this)

Fix turns where segments arrive at an intersection point, or leave

---

include/boost/geometry/algorithms/area_result.hpp
include/boost/geometry/geometries/point.hpp
include/boost/geometry/geometries/variant.hpp
include/boost/geometry/srs/projections/dpar.hpp
include/boost/geometry/strategies/comparable_distance_result.hpp
include/boost/geometry/strategies/default_length_result.hpp
include/boost/geometry/strategies/distance_result.hpp

This PR adds fixes/workarounds for two problems that cause compilation failures with clang 3.5-3.9:
1. 3.5 - Class template partial specialization cannot be deduced for `boost::variant` and parameter pack. The solution to that is to use `BOOST_VARIANT_ENUM_PARAMS` in specializations. The list of types can be analyzed with variadic templates afterwards.
2. 3.5-3.9 - The instantiation of `std::is_constructible` for 2d `model::point` and 3 parameters causes the compilation error related to the initialization of 2-element array with too many elements. The solution to that is to enable the constructor only if the number of arguments is lesser or equal to `Dimension`. 
See the [regression matrix](https://www.boost.org/development/tests/develop/developer/geometry.html) for details.
Note that the …

Fixes/workarounds for clang 3.5-3.9

---

meta/libraries.json

The "cxxstd" json field is being added to each Boost library's meta json information for libraries whose minumum C++ standard compilation level is C++11 on up. The value of this field matches one of the values for 'cxxstd' in Boost.Build. The purpose of doing this is to provide information for the Boost website documentation for each library which will specify the minimum C++ standard compilation that an end-user must employ in order to use the particular library. This will aid end-users who want to know if they can successfully use a Boost library based on their C++ compiler's  compilation level, without having to search the library's documentation to find this out.

Add "cxxstd" json field to meta/libraries.json

---

example/05_b_overlay_linestring_polygon_example.cpp
example/c05_custom_point_pointer_example.cpp
example/c08_custom_non_std_example.cpp

The `example/c03_custom_linestring_example.cpp` requires change from PR #786
These changes make all examples compile again.
Fixes #784

Catch up examples with addition of robustness policy and others

---

include/boost/geometry/extensions/algorithms/parse.hpp

The change to `dms_parser` was applied in PR #394
------
This PR is required to make all examples compile, see #787

Catch up with dms_parser change from function call operator to apply

---

include/boost/geometry/strategies/spherical/side_by_cross_track.hpp
test/algorithms/Jamfile

This PR fixes some tests that fail after merging https://github.com/boostorg/geometry/pull/756
See also https://app.circleci.com/pipelines/github/vissarion/geometry/58/workflows/44e84067-89f7-4938-947f-006156956840

[strategies] [test] Fix spherical cross track and convex hull tests

---

include/boost/geometry/extensions/algorithms/detail/overlay/dissolver.hpp

Reported via ML https://lists.boost.org/geometry/2021/01/3829.php

Fix MSVC warning C4267: '=': conversion from 'size_t' to 'int'

---

include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
include/boost/geometry/algorithms/detail/buffer/line_line_intersection.hpp
include/boost/geometry/arithmetic/infinite_line_functions.hpp
include/boost/geometry/geometries/infinite_line.hpp
include/boost/geometry/strategies/cartesian/buffer_side_straight.hpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_polygon.cpp

Issue #803 had an artifact, generated on nearly collinear lines in the buffer
The intersection point (calculated from the green and the blue line) was quite off (magenta) as you can see below.
The artifact itself is also visible below.
Now I added an option to calculate the intersection point from either those lines, or from the angle bisector between the two perpendicular lines, so from the green line and the center between the two orange lines (here they're nearly collinear)

[buffer] fix case for issue 803 

---

include/boost/geometry/formulas/geographic.hpp

This PR fixes some tests failing after merging https://github.com/boostorg/geometry/pull/801

Fix vec_normalize namespace

---

doc/html/index.html
doc/imports.qbk
doc/quickref.xml
doc/reference/io/from_wkt.qbk
doc/reference/io/read_wkt.qbk
doc/reference/io/to_wkt.qbk
doc/reference/io/wkt.qbk
doc/src/examples/io/Jamfile
doc/src/examples/io/from_wkt.cpp
doc/src/examples/io/to_wkt.cpp
doc/src/examples/io/wkt.cpp
include/boost/geometry/io/wkt/read.hpp
include/boost/geometry/io/wkt/write.hpp
test/io/wkt/wkt.cpp

This PR fixes #654 . It adds the following:
- `to_wkt`: This function converts the given geometry to wkt string and returns it instead of modifying a stringstream taken as input like `wkt`.
- `from_wkt`: This function returns the geometry obtained by parsing a wkt string instead of taking in a geometry variable as parameter and storing the geometry in it.
- tests: Tests for both `to_wkt` and `from_wkt` are provided with basically follow the template of already implemented `read_wkt` and `wkt` tests.
- examples and documentation: Example usage of both have been added and documentation has been updated.
This PR is now ready to be reviewed and then merged.

Symmetrizing read/write wkt

---

test/algorithms/area/area_sph_geo.cpp

After merging https://github.com/boostorg/geometry/pull/801 some of the tests started to fail.
This PR changes error margins for these cases.
I don't know if this is a temporary or permanent solution. @vissarion do you think this is worth investigating more?

[test][area] Tweak error thresholds for small areas.

---

include/boost/geometry/algorithms/detail/overlay/approximately_equals.hpp
include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp
include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/get_clusters.hpp
include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp
include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_linestring.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/buffer/buffer_polygon.cpp
test/algorithms/detail/Jamfile
test/algorithms/detail/approximately_equals.cpp
test/algorithms/overlay/Jamfile
test/algorithms/overlay/get_clusters.cpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp
test/geometry_test_common.hpp

This fixes a part (around 30%) of the remaining errors in the recursive buffer check
There are some (small) changes in expectations, because the previous clustering algorithm did not generate a cluster for some cases (for example in the distance_zero case) while it should have (they are at exactly the same locations).
Apart from fixing several buffer cases, the new algorithm is also much simpler and more maintainable.

[clusters] detection is refactored to a simpler sweeping algorithm

---

include/boost/geometry/policies/robustness/segment_ratio.hpp
include/boost/geometry/strategies/cartesian/intersection.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp

This fixes bug #838 (the visible artifact was an intersection point far away from both segments)
It also fixes some other errors (probably artifacts)

[intersection] fix intersection points outside of the segments

---

include/boost/geometry/index/detail/serialization.hpp

This PR fixes https://github.com/boostorg/geometry/issues/865

Fix rtree serialization load for 1-level tree with number of elements lesser than min.

---

include/boost/geometry/strategy/cartesian/side_robust.hpp
test/algorithms/overlay/get_clusters.cpp

This PR fixes compilation errors caused by narrowing conversions in initializer lists.
Related:
- https://github.com/boostorg/geometry/pull/873
- https://github.com/boostorg/geometry/issues/849

Fix initializer lists

---

include/boost/geometry/index/detail/predicates.hpp
include/boost/geometry/index/detail/rtree/visitors/distance_query.hpp
include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
include/boost/geometry/index/predicates.hpp
include/boost/geometry/index/rtree.hpp

Before this PR unneeded nodes were traversed by the query iterator and by extension many unneeded neighbours were taken into consideration. This fixes: https://github.com/boostorg/geometry/issues/867
Additional improvement is that the neighbors that were already handled are not sorted again.
This PR also changes type `unsigned` to `size_t` in several places.

Fix traversing of the rtree during incremental knn query.

---

include/boost/geometry/core/config.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/difference/test_difference.hpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/intersection/intersection_multi.cpp
test/algorithms/set_operations/union/union_multi.cpp
test/geometry_test_common.hpp

The objective of this PR is removing the define `BOOST_GEOMETRY_USE_KRAMER` because it's always used.
Last year I tried to change that by using the generic form instead. That's possible but didn't give much improvements and some regressions, and needed more and more conditions and tuning.
So it's redundant now, and I applied some other changes in tests, for example in difference where the symmetric difference was actually never tested without rescaling (I forgot that earlier).

[test] remove the non used KRAMER define and some other changes in testing is_valid

---

doc/src/examples/algorithms/is_valid_failure.cpp

The [example](https://www.boost.org/doc/libs/1_76_0/libs/geometry/doc/html/geometry/reference/algorithms/is_valid/is_valid_2_with_failure_value.html#geometry.reference.algorithms.is_valid.is_valid_2_with_failure_value.example) checking if invalid geometry was fixable with `bg::correct` incorrectly assumes that all failures are fixable, instead of checking for specific failure reasons, as it was purporting to do.
It looks like it was written in bitflag-style, but [`validity_failure_type`](https://www.boost.org/doc/libs/1_76_0/libs/geometry/doc/html/geometry/reference/enumerations/validity_failure_type.html) is not a bitflag field (maybe it used to be?)
Discovered in https://github.com/cctbx/dxtbx/pull/411 as this raised a compiler warning from `-Wint-in-bool-context`:
```
geom_example.cpp: …
```

Fix error checking for failure type in example

---

test/algorithms/convex_hull/convex_hull_robust.cpp

Fix tests after non robust convex hull (using the fast non robust orientation predicate) returns wrong results, which is OK and expected since the computation is non robust.

Fix robust convex hull tests

---

include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
test/algorithms/buffer/buffer_multi_linestring.cpp

On macos-11 with clang-12.0.5 for this case:
```
cmls_t mls;
bg::read_wkt("MULTILINESTRING((0 10,10 0),(10 0,0 0),(0 0,10 10))", mls);
cmpo_t mpo;
bg::buffer(mls, mpo,
bg::strategy::buffer::distance_symmetric<double>(100),
bg::strategy::buffer::side_straight(),
bg::strategy::buffer::join_miter(10),
bg::strategy::buffer::end_round(32),
bg::strategy::buffer::point_circle(32));
```
wrong buffer is generated, should be green, is blue (this is a regression):
On this platform slightly different pieces and turns are generated. They are close to these generated for msvc-14.1:
So with msvc-14.1 there are two clusters: (turns 3 and 4) and (turns 22 and 31). With macos-11+clang-12 the former cluster is not generated because turns 3 and 4 are marked as not traversable due to the check of the min …

Fix buffer for macos-11, clang-12.0.5, x86-64

---

test/algorithms/set_operations/difference/difference_linear_linear.cpp
test/algorithms/set_operations/difference/test_difference_linear_linear.hpp
test/algorithms/set_operations/test_set_ops_linear_linear.hpp
test/to_svg.hpp

This
* excludes cases failing for rescaling
* removes duplicate testcases (all was already tested in all directions)
* adds settings to explicitly just skip some of the cases
* fixes svg and other small changes
There are still some cases failing without rescaling, to be investigated further

test: add and use test settings

---

test/algorithms/buffer/test_buffer_svg.hpp
test/algorithms/centroid.cpp
test/algorithms/overlay/get_turns_areal_areal.cpp
test/algorithms/overlay/get_turns_linear_areal.cpp
test/algorithms/overlay/get_turns_linear_linear.cpp
test/algorithms/overlay/get_turns_linear_linear_sph.cpp
test/algorithms/relate/relate_areal_areal.cpp
test/algorithms/relate/relate_linear_areal.cpp
test/algorithms/relate/relate_linear_linear.cpp
test/algorithms/relate/relate_linear_linear_sph.cpp
test/algorithms/relate/relate_pointlike_geometry.cpp
test/algorithms/set_operations/test_set_ops_pointlike.hpp
test/to_svg.hpp

Small PR removing unused / commented svg generation in tests, and making sure all tests compile with TEST_WITH_SVG, and enhancing the SVG's for linestrings (diff lin/lin)

[test] cleanup svg generation

---

include/boost/geometry/strategy/spherical/envelope_segment.hpp
test/algorithms/envelope_expand/envelope_on_spheroid.cpp

This PR proposes a fix for https://github.com/boostorg/geometry/issues/935

Fix spherical and geographic envelope for near meridian segments

---

include/boost/geometry/algorithms/sym_difference.hpp
include/boost/geometry/strategies/convex_hull/cartesian.hpp
include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
include/boost/geometry/strategy/cartesian/side_robust.hpp
test/algorithms/convex_hull/Jamfile
test/algorithms/overlay/Jamfile
test/algorithms/overlay/get_turns_linear_linear.cpp
test/algorithms/overlay/relative_order.cpp
test/algorithms/set_operations/alternative_robustness_strategy.hpp
test/algorithms/set_operations/intersection/intersection_linear_linear.cpp
test/algorithms/set_operations/intersection/test_intersection_linear_linear.hpp
test/strategies/spherical_side.cpp

This PR (edited):
- removes the define such that the new `side_triangle` is now always the default strategy ( (to be researched further why the robust fails for some obvious cases, as discussed with @vissarion ).
- instead, for the convex_hull, the umbrella_strategy defines still `side_robust`
After this PR:
- convex hull passes again, when `NO_ROBUSTNESS` is defined
- get_turns_linear_linear passes again, when `NO_ROBUSTNESS` is defined
- there is less dependency on the define `BOOST_GEOMETRY_USE_RESCALING`

Use side_by_triangle by default

---

include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp
include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp
include/boost/geometry/algorithms/detail/overlay/get_distance_measure.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/strategies/buffer/cartesian.hpp
include/boost/geometry/strategies/buffer/geographic.hpp
include/boost/geometry/strategies/buffer/spherical.hpp
test/algorithms/buffer/buffer_multi_point.cpp
test/algorithms/buffer/buffer_piece_border.cpp
test/algorithms/buffer/test_buffer_geo.hpp

Furthermore:
- pass umbrella strategy to some algorithms which were using default strategy.
- derive buffer umbrella strategies from distance strategies.

Propagate umbrella strategy in buffer and overlay.

---

test/algorithms/closest_points/common.hpp
test/algorithms/closest_points/pl_l.cpp

- remove #define
- alter error thresholds, otherwise the tests are failing with msvc-14.1

Fix closest points test

---

extensions/test/algorithms/dissolve.cpp
extensions/test/triangulation/side_robust.cpp
include/boost/geometry/extensions/algorithms/detail/overlay/dissolver.hpp
include/boost/geometry/extensions/algorithms/dissolve.hpp

Fix for https://github.com/boostorg/geometry/issues/944
- fix compilation errors in dissolve caused by the addition of umbrella strategies
- replace BOOST_FOREACH in tests
- fix compilation errors in triangulation/side_robust test

Fix dissolve and side_robust test

---

include/boost/geometry/algorithms/simplify.hpp
test/algorithms/simplify.cpp

Fix for https://github.com/boostorg/geometry/issues/956
Furthermore:
- avoid duplicating closing point for closed rings while rotating the range
- use more efficient strategy while calculating index of opposite point

Fix simplify for open rings and improve it

---

include/boost/geometry/algorithms/detail/disjoint/segment_box.hpp
include/boost/geometry/algorithms/detail/envelope/areal.hpp
include/boost/geometry/algorithms/detail/envelope/geometry_collection.hpp
include/boost/geometry/algorithms/detail/envelope/range.hpp
include/boost/geometry/strategies/envelope/cartesian.hpp
include/boost/geometry/strategies/envelope/geographic.hpp
include/boost/geometry/strategies/envelope/spherical.hpp
include/boost/geometry/strategies/spherical/distance_segment_box.hpp
include/boost/geometry/strategy/cartesian/envelope_boxes.hpp
include/boost/geometry/strategy/cartesian/envelope_range.hpp
include/boost/geometry/strategy/geographic/envelope_range.hpp
include/boost/geometry/strategy/spherical/envelope_boxes.hpp
include/boost/geometry/strategy/spherical/envelope_range.hpp
include/boost/geometry/views/closeable_view.hpp
include/boost/geometry/views/detail/closed_clockwise_view.hpp
include/boost/geometry/views/reversible_view.hpp
test/algorithms/envelope_expand/envelope_on_spheroid.cpp

This PR fixes spherical and geographic envelope for polygons containing poles. Currently the envelope of a polygon is the envelope of the linear ring. If a polygon is a polar cap then the result is incorrect because the envelope should contain the pole even if it's above or below linear ring.
If an envelope covers the whole longitude range then poles are checked to see whether or not they are inside the ring. This check is done with `point_in_poly` strategy with custom `pole_side` strategy to avoid costly calculation done in regular side strategies.
Additional changes:
- envelope strategy previously used for linear and polygonal geometries as well as multi geometries is divided into three strategies: one for linestring, one for ring and one for range of boxes which is used for multi …

Fix envelope of polygon containing pole.

---

include/boost/geometry/index/detail/algorithms/content.hpp
include/boost/geometry/index/detail/algorithms/margin.hpp

Fix for https://github.com/boostorg/geometry/issues/971

Promote content and margin result to double instead of long double

---

include/boost/geometry/algorithms/detail/overlay/get_turn_info_helpers.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/sections/section_functions.hpp
include/boost/geometry/geometries/register/point.hpp
test/algorithms/detail/sections/sectionalize_const.cpp
test/algorithms/overlay/Jamfile
test/algorithms/overlay/get_turns_const.cpp
test/test_geometries/const_point.hpp

Fixes #983 
After this, the using operations such as `disjoint` do still not work yet - they need to use the `helper_geometry_type` internally to calculate turns, etc.

[fix] get_turns with const geometries

---

include/boost/geometry/srs/projections/proj/tmerc.hpp
test/srs/projection_interface_d.cpp
test/srs/projection_interface_s.cpp
test/srs/projection_selftest_cases.hpp
test/srs/transformation_interface.cpp

This PR adds exact (or Poder/Engsager) implementations for ellipsoidal `tmerc` projection. It fixes several tests that had wrong/inaccurate results. Currently the old implementation (approximate or Evenden/Snyder) is commented out. 
For reference see https://github.com/OSGeo/PROJ/blob/master/src/projections/tmerc.cpp

[srs] Accurate methods for ellipsoidal tmerc

---

include/boost/geometry/policies/robustness/segment_ratio.hpp

Fix c++20 compilation errors related to conditional expression with int and floating_point_type
A floating_point_type with implicit conversions can lead to this C++20 compilation error:
boost\geometry\policies\robustness\segment_ratio.hpp(232,1): error C2445: result type of conditional expression is ambiguous: types 'int' and '<floating_point_type>' can be converted to multiple common types

Fix c++20 compilation errors related to conditional expression

---

include/boost/geometry/algorithms/detail/disjoint/areal_areal.hpp
include/boost/geometry/algorithms/detail/disjoint/linear_areal.hpp
include/boost/geometry/algorithms/detail/disjoint/linear_linear.hpp
include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
include/boost/geometry/algorithms/detail/overlay/linear_linear.hpp
include/boost/geometry/algorithms/detail/relate/areal_areal.hpp
include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp
include/boost/geometry/algorithms/detail/relate/follow_helpers.hpp
include/boost/geometry/algorithms/detail/relate/linear_areal.hpp
include/boost/geometry/algorithms/detail/relate/linear_linear.hpp
include/boost/geometry/algorithms/detail/relate/turns.hpp
include/boost/geometry/algorithms/detail/touches/implementation.hpp
test/algorithms/overlay/test_get_turns.hpp
test/algorithms/relate/Jamfile
test/algorithms/relate/relate_const.cpp
test/algorithms/set_operations/check_turn_less.hpp
test/algorithms/set_operations/test_get_turns_ll_invariance.hpp
test/robustness/overlay/areal_areal/interior_triangles.cpp
test/test_geometries/const_point.hpp
test/to_svg.hpp

Fixes #985 
Some pieces of the touched code become a bit simpler by this (for example avoiding an extra conversion).
There are some renamings as well, such as `get_turns` (this was really inconvenient, there is a namespace and a free function as well - and this does something different - so I call it `turn_retriever` now) and `define_turn_operation_type` i/o `turn_operation_type` (because that is there as well).
Also there are some white space changes (at end of lines), fixed by my editor.

Fix const disjoint

---

doc/reference/algorithms/covered_by.qbk
doc/reference/algorithms/densify.qbk
doc/reference/algorithms/perimeter.qbk
doc/reference/algorithms/simplify.qbk

This PR updates 4 broken links to http://www.postgis.org/... to point to https://postgis.net/... instead.

Change 4 broken postgis.org links to postgis.net

---

include/boost/geometry/strategies/geographic/distance_cross_track.hpp

This is a fix for https://github.com/boostorg/geometry/issues/1004
ps. some trailing whitespaces are removed

Fix auto return in distance_cross_track strategy

---

include/boost/geometry/algorithms/line_interpolate.hpp

If I understood line_interpolate correctly, the early termination condition is intended to apply to all output geometry types that are single points rather than just the point type of the input range. I think this fixes #1000 .

Fix line_interpolate termination condition for single points.

---

include/boost/geometry/algorithms/detail/make_rtree.hpp
include/boost/geometry/algorithms/difference.hpp
include/boost/geometry/views/detail/geometry_collection_view.hpp
test/algorithms/set_operations/difference/Jamfile
test/algorithms/set_operations/difference/difference_gc.cpp

Add also:
- `make_rtree()` utility making an rtree of GC elements
- `geometry_collection_view<>` allowing to represent any geometry as GC
- tests
This PR also adds support for difference(g1, g2) where topological dimension of g1 is greater than of g2 so the result is always g1, e.g. Polygon \ MultiPoint.

Add support for GeometryCollection in difference()

---

include/boost/geometry/strategies/cartesian/side_rounded_input.hpp
include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
test/strategies/Jamfile
test/strategies/side_rounded_input.cpp

Add algorithm created by @tinko92 , including a unit test.
The robustness test is not committed anymore in this PR (wip).
The next PR (for slopes) will use this side algorithm.
Old description:
---------------------------------------------------------------------------------------------------
Add robustness test for comparing intersection with sides, for the problem described in #993 
This test generates random segments and calculate the intersection points between them (if any).
If there is one, it uses a side calculation to verify if the intersection point is determined as on-both-segments.
Like this:
It uses many side strategies we have (for cartesian) plus the new one of @tinko92 
The new one seems to be the best, by far:
* it returns nearly always 0 (correct) for the intersection …

[side] added side_rounded_input and robustness test

---

include/boost/geometry/algorithms/simplify.hpp
test/algorithms/simplify.cpp

Requested in this comment: https://github.com/boostorg/geometry/commit/0f72af95f0ac94f94022c6e4b7831895c2291dde#commitcomment-76745077

Allow different input and output types in simplify

---

include/boost/geometry/algorithms/detail/relate/de9im.hpp
include/boost/geometry/algorithms/detail/relate/implementation_gc.hpp
include/boost/geometry/algorithms/detail/touches/implementation.hpp
test/algorithms/touches/touches_gc.cpp

Avoid -1 to size_t conversion while instantiating static mask. Relate is now called with proper mask based on run-time topological dimension of GCs just like it's done with other relational operations which masks depend on dimensions of arguments.
Also fix warning in relate.

Fix compilation of touches for geometry collections with gcc-10

---

include/boost/geometry/index/distance_predicates.hpp
include/boost/geometry/index/predicates.hpp
include/boost/geometry/index/rtree.hpp

Fix access specifier preventing use of experimental iterators.
Allow more granular control over enabled experimental features.

[index] Fix and improve rtree experimental features

---

Jamfile

The library requires C++14 so it should not even be tried to build with any older `cxxstd`
IOW, `b2 cxxstd=11 libs/geometry/test` will build nothing.
Related to discussion in #1012

build: Add cxx14 requirements to root Jamfile

---

doc/release_notes.qbk
extensions/meta/libraries.json
index/meta/libraries.json
meta/libraries.json

This PR tracks the progress of bugfixes to be released in 1.81. Currently including only merged PRs and waiting for https://github.com/boostorg/geometry/pulls?q=is%3Aopen+is%3Apr+milestone%3A1.81. Then this PR will be updated accordingly.

Update release notes for 1.81

---

.github/workflows/minimal.yml

Github actions is failing currently. This is due to a change in ubuntu version used by the CI. It used to be 20.04 (see https://github.com/boostorg/geometry/actions/runs/3591991978/jobs/6047189522#step:1:4) but now it is 22.04.1 (see https://github.com/boostorg/geometry/actions/runs/3594906729/jobs/6179253324#step:1:4). This is expected since `ubuntu-latest` can be either 20.04 or 22.04 depending on the runner (see https://github.com/actions/runner-images#ongoing-migrations). 
This PR changes the runner from `ubuntu-latest` to `ubuntu-20.04`. If we want to switch to `22.04` we either a) have to fix issues with some old versions of compilers e.g. `clang-3.9` that cannot be installed in 22.04 (`libc6-dev : Breaks: libgcc-7-dev (< 7.5.0-6~) but 7.3.0-16ubuntu3 is to be installed`) or b) …

Fix github actions

---

doc/release_notes.qbk
include/boost/geometry/io/wkt/detail/prefix.hpp
include/boost/geometry/io/wkt/detail/wkt_multi.hpp
include/boost/geometry/io/wkt/read.hpp
include/boost/geometry/io/wkt/write.hpp
include/boost/geometry/multi/io/wkt/detail/prefix.hpp
test/algorithms/for_each.cpp
test/io/wkt/wkt.cpp
test/io/wkt/wkt_multi.cpp

This PR does the following:
- it supports tabs and newlines in WKT (see #705, that is how I noticed it - but i/o warning we better just support it)
- there were some todo's about EMPTY, they are now checked
- doing that, the inconsistency of writing empty polygons (`(())` vs `()`) is removed
- fixing that, it removes the need of specific prefixes with opening brackets
- fixing that, the existing prefixes are now used throughout such that for example `"POINT"` is defined only once
- fixing that, I noticed a copy of the prefixes in an old unused headerfile, the multi headerfiles are now marked as deprecated
It's a small breaking change because an empty polygon is now streamed as `POLYGON()` but I think that will be no problem.

[wkt] support tabs, newlines and code cleanup

---

test/algorithms/envelope_expand/envelope_on_spheroid.cpp
test/algorithms/envelope_expand/expand_on_spheroid.cpp

This PR fixes some failing tests in [circleCI](https://app.circleci.com/pipelines/github/boostorg/geometry/393/workflows/0f08835f-b25a-4112-b290-47348ca4a762/jobs/19548) by relaxing the test dataset. In particular, it tests against a slightly smaller box.
The commit that introduced that fail was https://github.com/boostorg/geometry/commit/092ab9da349dd0dab8b610407b0275b192d0477c in particular the replacement of boost::minmax_element with std::minmax_element. Actually, the invalid box was already there before that commit but accidentally the use of boost::minmax_element had made valid() return true.
Related issue https://github.com/boostorg/geometry/issues/1148

[test] Relaxing envelope test due to invalid box computation

---

include/boost/geometry/algorithms/detail/calculate_point_order.hpp

This allows to compile the algorithm with non-mutable rings.

[algorithms] Check const Ring concept in calculate_point_order

---

include/boost/geometry/algorithms/densify.hpp
include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp
include/boost/geometry/algorithms/detail/is_valid/linear.hpp
include/boost/geometry/algorithms/detail/is_valid/multipolygon.hpp
include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
include/boost/geometry/io/wkt/write.hpp
include/boost/geometry/policies/is_valid/failing_reason_policy.hpp
include/boost/geometry/util/constexpr.hpp

This is a proposal adding conditional support of C++17 `if constexpr`. I modified only several files for now so we can start a discussion. If we have an agreement I'll modify other places.
My intention was to have a solution as close as possible to the original language feature and to keep `if` keyword so editors can highlight it as usual, i.e.:
```
if constexpr (static_condition)
```
vs
```
if BOOST_GEOMETRY_CONSTEXPR (static_condition)
```
It's a followup of https://github.com/boostorg/geometry/pull/1160

Add if constexpr macro and replace condition macro.

---

include/boost/geometry/core/config.hpp

As discussed in https://github.com/boostorg/geometry/issues/1163 this PR updates the warning message.

Update rescaling deprecation warning message

---

.circleci/config.yml
.circleci/run_test.sh

Following the discussion [here](https://github.com/boostorg/geometry/discussions/1155) this PR proposes:
- to update the circleCI image to a next-gen convenience image (read [this](https://circleci.com/docs/next-gen-migration-guide/) for the advantages of this change). Moreover, following the discussion [here](https://github.com/boostorg/geometry/pull/1147) the compiler is set to gcc-6 to possible catch library issues,
- add ~~a closing job to circleCI to cover~~ missing tests.

Update circleCI scripts and image

---

include/boost/geometry/algorithms/detail/convex_hull/graham_andrew.hpp
include/boost/geometry/algorithms/detail/disjoint/multipoint_geometry.hpp
include/boost/geometry/algorithms/detail/distance/segment_to_box.hpp
include/boost/geometry/algorithms/detail/is_simple/multipoint.hpp
include/boost/geometry/algorithms/detail/is_valid/complement_graph.hpp
include/boost/geometry/algorithms/detail/is_valid/debug_complement_graph.hpp
include/boost/geometry/algorithms/detail/is_valid/polygon.hpp
include/boost/geometry/algorithms/detail/overlay/pointlike_pointlike.hpp
include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp
include/boost/geometry/algorithms/detail/relate/multi_point_geometry.hpp
include/boost/geometry/algorithms/detail/relate/point_point.hpp
include/boost/geometry/algorithms/detail/relate/topology_check.hpp
include/boost/geometry/algorithms/detail/within/multi_point.hpp
include/boost/geometry/algorithms/merge_elements.hpp
include/boost/geometry/policies/compare.hpp
include/boost/geometry/strategies/compare.hpp
include/boost/geometry/strategies/convex_hull/cartesian.hpp
include/boost/geometry/strategies/convex_hull/geographic.hpp
include/boost/geometry/strategies/convex_hull/spherical.hpp
include/boost/geometry/strategies/relate/cartesian.hpp
include/boost/geometry/strategies/relate/geographic.hpp
include/boost/geometry/strategies/relate/spherical.hpp
include/boost/geometry/strategies/spherical/compare.hpp
include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
test/algorithms/convex_hull/convex_hull_robust.cpp
test/algorithms/set_operations/intersection/intersection_linear_linear.cpp
test/cs_undefined/test_relops.hpp

This PR propose a fix for https://github.com/boostorg/geometry/issues/1158
First, it enables passing (umbrella) strategies to less policy. Then different (umbrella) strategies can parameterize the less policy by different compare strategy. 
For, example floating point comparison in convex hull strategies does *not* need to be done approximately. Relate strategies still use the approximate comparison of fp numbers (`math::equals()` function).
Side note: I am not sure if approximate comparison of numbers is needed for relate strategy. I just left it as is in order for the tests to pass, but I think it needs some investigation. Related issue https://github.com/boostorg/geometry/issues/1148 
Next steps (to be implemented in new PRs)
- do the same for `greater` and `equal_to`
- move code from …

Fix convex hull issue by passing compare strategies

---

doc/release_notes.qbk

This are the release notes for 1.83. Please review asap so I can prepare the release.
Waiting for approval for 
- https://github.com/boostorg/geometry/pull/1177
- https://github.com/boostorg/geometry/pull/1162
in order to get included into the release.

Update release notes for 1.83

---

include/boost/geometry/algorithms/centroid.hpp
include/boost/geometry/algorithms/detail/has_self_intersections.hpp
include/boost/geometry/algorithms/detail/overlay/get_turn_info.hpp
include/boost/geometry/algorithms/detail/overlay/inconsistent_turns_exception.hpp
include/boost/geometry/core/exception.hpp
include/boost/geometry/extensions/gis/io/shapefile/read.hpp
include/boost/geometry/extensions/gis/io/shapelib/shape_creator.hpp
include/boost/geometry/extensions/gis/io/wkb/detail/parser.hpp
include/boost/geometry/io/wkt/read.hpp
include/boost/geometry/srs/projections/exception.hpp
include/boost/geometry/srs/projections/str_cast.hpp
index/test/rtree/exceptions/test_throwing.hpp
index/test/rtree/exceptions/test_throwing_node.hpp
test/core/assert.cpp

As boost::geometry mandates C++14 since 1.75, I assume this can be merged in C++03-incompatible form.

Modernize noexcept specifications

---

include/boost/geometry/formulas/karney_inverse.hpp
include/boost/geometry/index/detail/rtree/node/variant_dynamic.hpp
include/boost/geometry/index/detail/rtree/node/variant_static.hpp
include/boost/geometry/index/detail/rtree/node/weak_dynamic.hpp
include/boost/geometry/index/detail/rtree/node/weak_static.hpp
include/boost/geometry/index/detail/utilities.hpp
include/boost/geometry/index/detail/varray.hpp
include/boost/geometry/index/rtree.hpp
include/boost/geometry/util/series_expansion.hpp
index/test/rtree/exceptions/test_throwing_node.hpp

`boost::swap` is deprecated and will be removed. Use `boost::core::invoke_swap` as a replacement.
Also add missing includes.

Switch to `boost::core::invoke_swap`. Add missing includes.

---

include/boost/geometry/strategies/cartesian/centroid_average.hpp

Msvc complains about the conversion from integer to floating point at some higher warning level.

[strategies] Fix msvc conversion warning in centroid::average

---

include/boost/geometry/formulas/meridian_direct.hpp
test/algorithms/buffer/buffer_linestring_geo.cpp
test/algorithms/buffer/buffer_piece_border.cpp
test/algorithms/set_operations/intersection/intersection_integer.cpp
test/algorithms/set_operations/union/union_issues.cpp

This fixes a couple of warnings to declutter the output of running `b2 test` with GCC 13 or Clang 16 (and possibly other versions which I do not have installed):
* a missing template keyword warning with GCC (which looks like a compiler bug to me but the workaround only costs two brackets),
* some warnings for comparing signed and unsigned integers,
* missing parentheses warnings,
* an unused parameter warning (just commented out because the lining that would have used it is also just commented out).
The remaining warnings (with the compilers that I have) come from Boost.Polygon and Boost.Test.

Fixes for miscellaneous gcc/clang warnings in the test suite.

---

test/algorithms/overlay/get_distance_measure.cpp

Log is listed as follows.
```
Running 1 test case...
test/algorithms/overlay/get_distance_measure.cpp(60): error: in "test_main_caller( argc_ argv )": Case: issue_1183_3 ctype: e tr_side: -1 dm_side: 1
test/algorithms/overlay/get_distance_measure.cpp(60): error: in "test_main_caller( argc_ argv )": Case: issue_1183_4 ctype: e tr_side: -1 dm_side: 1
test/algorithms/overlay/get_distance_measure.cpp(60): error: in "test_main_caller( argc_ argv )": Case: issue_1183_5 ctype: e tr_side: -1 dm_side: 0
test/algorithms/overlay/get_distance_measure.cpp(60): error: in "test_main_caller( argc_ argv )": Case: issue_1183_6 ctype: e tr_side: -1 dm_side: 0
test/algorithms/overlay/get_distance_measure.cpp(60): error: in "test_main_caller( argc_ argv )": Case: issue_1183_7 ctype: e tr_side: -1 dm_side: 0 …
```

Fix get_distance_measure test failure using MSVC

---

.github/workflows/documentation.yml
.github/workflows/headers.yml
.github/workflows/minimal.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command

---

include/boost/geometry/strategies/convex_hull/cartesian.hpp

This changes the default side strategy for convex_hull for cartesian coordinates so that it uses an exact comparison to zero for the side value. This is IMHO the only way to use that strategy to guarantee exact (and thereby consistent) results, which was the intention behind the strategy. The motivation is issue #1208 , which is fixed by this change. I see no testcase breaking.
From git blame, I don't see the motivation for the current non-exact comparison. If it was to be more lenient in is_convex, which uses the same umbrella strategy, then maybe those should be separate umbrella strategies. I think in the construction of the hull this non-robustness is more problematic. If it was done like this to avoid near-collinear points on edges of the output, maybe there should be a separate …

Use fp_equals comparison in side_strategy for convex_hull.

---

include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
include/boost/geometry/algorithms/detail/overlay/sort_by_side.hpp
include/boost/geometry/algorithms/detail/overlay/traversal.hpp
include/boost/geometry/algorithms/detail/overlay/traversal_ring_creator.hpp
test/algorithms/overlay/copy_segment_point.cpp
test/algorithms/overlay/sort_by_side.cpp
test/algorithms/overlay/sort_by_side_basic.cpp

Small PR, passing the strategy i/o the side strategy in several places, which was a TODO already.
Also documents sort_by_side better.
It is a preparation step for a next PR.
This should not change anything (apart from users, by chance using `sort_by_side` - but it's all in namespace `detail`, so not considered as a breaking change)

pass strategy to sort by side

---

test/algorithms/is_simple.cpp
test/algorithms/is_valid.cpp
test/util/rational.cpp

Following comment https://github.com/boostorg/geometry/pull/1237#discussion_r1501810625 this PR adds removed tests for is_simple and is_valid with geometries whose coordinates are close to the maximum double. 
The tests are passing with the fix of https://github.com/boostorg/geometry/pull/1237 but the results are different i.e. the intersection does not create NaN coordinates, it is more accurate but still can create invalid geometries.
This PR also fixes a compile error in tests (wrong namespace for numeric_cast).

Fixes compile error in tests and add removed tests for is_simple and is_valid

---

include/boost/geometry/algorithms/line_interpolate.hpp

Broken in this PR: https://github.com/boostorg/geometry/pull/1247

[line_interpolate] Fix infinite loop

---

include/boost/geometry/algorithms/detail/sections/sectionalize.hpp

[fix] replace decltype by typename for some compilers

---

include/boost/geometry/index/detail/rtree/visitors/insert.hpp

This PR fixes the compilation error 
`error: macro "BOOST_GEOMETRY_CONSTEXPR" passed 2 arguments, but takes just 1`
introduced by cb2f53d9d90f9d602833e87ebf9699890b4f74d7

Fix BOOST_GEOMETRY_CONSTEXPR call in index

---

include/boost/geometry/algorithms/detail/envelope/range_of_boxes.hpp
include/boost/geometry/strategy/spherical/expand_box.hpp
test/algorithms/envelope_expand/expand_on_spheroid.cpp

Fixes failing tests due to missing header files.

Add missing headers for is_inverse_spheroidal_coordinates function

---

include/boost/geometry/index/detail/rtree/visitors/insert.hpp

This PR fixes the issue discussed here: https://github.com/boostorg/geometry/pull/1265#discussion_r1543737915

Fix BOOST_GEOMETRY_CONSTEXPR call in index (including support for c++17)

---

include/boost/geometry/algorithms/append.hpp
include/boost/geometry/algorithms/area.hpp
include/boost/geometry/algorithms/assign.hpp
include/boost/geometry/algorithms/centroid.hpp
include/boost/geometry/algorithms/clear.hpp
include/boost/geometry/algorithms/convert.hpp
include/boost/geometry/algorithms/correct.hpp
include/boost/geometry/algorithms/correct_closure.hpp
include/boost/geometry/core/access.hpp
include/boost/geometry/core/closure.hpp
include/boost/geometry/core/coordinate_dimension.hpp
include/boost/geometry/core/coordinate_system.hpp
include/boost/geometry/core/coordinate_type.hpp
include/boost/geometry/core/cs.hpp
include/boost/geometry/core/geometry_id.hpp
include/boost/geometry/core/point_order.hpp
include/boost/geometry/core/point_type.hpp
include/boost/geometry/core/radius.hpp
include/boost/geometry/core/reverse_dispatch.hpp
include/boost/geometry/core/ring_type.hpp
include/boost/geometry/core/tag.hpp
include/boost/geometry/core/tag_cast.hpp
include/boost/geometry/core/tags.hpp
include/boost/geometry/core/topological_dimension.hpp
include/boost/geometry/util/type_traits.hpp
include/boost/geometry/util/type_traits_std.hpp

Plus:
Add C++17 variable templates for traits behind #ifdef
Use aliases in several algorithms

Add alias templates for core and util traits

---

include/boost/geometry/strategies/spherical/point_in_poly_winding.hpp
test/algorithms/covered_by/covered_by_sph_geo.cpp

Fix covered_by incorrect results for polygons with multiple defined points as a pole.
Resolves https://github.com/boostorg/geometry/issues/1279 (the special case arise as part of issue https://github.com/boostorg/geometry/issues/1161)

Fix covered_by incorrect results 

---

include/boost/geometry/strategies/spherical/closest_points_pt_seg.hpp

Currently it fails to compile due to multiple return types.

[strategies] Fix spherical closest_points strategy for PointOfSegment different than model::point

---

doc/index/make_qbk.py
doc/make_qbk.py

When `b2` invokes `doc/make_qbk.py`, it passes a relative path to the compiled `doxygen_xml2qbk` executable. This path becomes invalid if used from a directory different from doc, which may happen as `make_qbk.py` changes the current directory during its execution. Additionally, `doc/index/make_qbk.py` invokes `doxygen_xml2qbk` unqualified, which requires the executable to be in `PATH` and is never the case unless the user has pre-compiled and placed it accordingly.
To fix this, first resolve the paths to `doxygen` and `doxygen_xml2qbk` to absolute paths before changing the current directory. Additionally, pass the resolved path to `doxygen_xml2qbk` to `doc/index/make_qbk.py` via the `DOXYGEN_XML2QBK` environment variable.
Fixes https://github.com/boostorg/geometry/issues/1311.

Fix `doxygen_xml2qbk` execution from `make_qbk.py`

---

.github/workflows/documentation.yml

Following the suggestion [here](https://github.com/boostorg/geometry/pull/1312#issuecomment-2373918114) this is a simplification for the documentation CI script.

[ci] Simplify the documentation CI

---

test/algorithms/buffer/buffer_countries.cpp
test/algorithms/buffer/buffer_linestring.cpp
test/algorithms/buffer/buffer_linestring_aimes.cpp
test/algorithms/buffer/buffer_multi_linestring.cpp
test/algorithms/buffer/buffer_multi_point.cpp
test/algorithms/buffer/buffer_multi_polygon.cpp
test/algorithms/buffer/buffer_point.cpp
test/algorithms/buffer/buffer_polygon.cpp
test/algorithms/buffer/test_buffer.hpp
test/algorithms/check_validity.hpp
test/algorithms/set_operations/difference/difference.cpp
test/algorithms/set_operations/difference/difference_multi.cpp
test/algorithms/set_operations/difference/test_difference.hpp
test/algorithms/set_operations/intersection/intersection.cpp
test/algorithms/set_operations/intersection/intersection_multi.cpp
test/algorithms/set_operations/union/union.cpp
test/algorithms/set_operations/union/union_multi.cpp
test/geometry_test_common.hpp

This PR:
* removes `BoostGeometryWriteExpectedFailures` (it was to compare rescaling with / without)
* verifies failing tests
* where not failing anymore, removes the defines or conditions
There were several tests which now succeeds. I didn't bisect them, but it is good to have them enabled now for future PR's.

test: verify failures and remove some rescaling remainings

---

extensions/test/algorithms/dissolve.cpp
include/boost/geometry/algorithms/detail/buffer/buffer_policies.hpp
include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
include/boost/geometry/algorithms/detail/overlay/handle_colocations.hpp
include/boost/geometry/algorithms/detail/overlay/less_by_segment_ratio.hpp
include/boost/geometry/algorithms/detail/overlay/overlay.hpp
include/boost/geometry/extensions/algorithms/dissolve.hpp
test/algorithms/overlay/sort_by_side.cpp
test/robustness/overlay/buffer/recursive_polygons_buffer.cpp

This relatively small PR removes things and changes a few minor things.
It prepares the next PR which will change traversal.

refactor: removed unused functionality and minor changes preparing next PR

---

include/boost/geometry/strategies/cartesian.hpp
include/boost/geometry/strategies/centroid/cartesian.hpp
include/boost/geometry/strategies/centroid/geographic.hpp
include/boost/geometry/strategies/centroid/spherical.hpp
include/boost/geometry/strategies/geographic.hpp
include/boost/geometry/strategies/geographic/distance_cross_track.hpp
include/boost/geometry/strategies/geographic/distance_cross_track_box_box.hpp
include/boost/geometry/strategies/index/cartesian.hpp
include/boost/geometry/strategies/index/geographic.hpp
include/boost/geometry/strategies/index/spherical.hpp
include/boost/geometry/strategies/spherical.hpp
include/boost/geometry/strategies/spherical/distance_cross_track_box_box.hpp

The getters are missing for `centroid` and `closest_points` in `index` and global umbrella strategies preventing them to be passed to these algorithms and rtree.
I divided centroid into detail part and official part derived from base. It works for now because centroid doesn't have proper strategies for spherical and geographic. After they are added and e.g. geographic one uses `Formula` and `Spheroid` we'll probably have to implement this differently.

Fix several strategies (add getters, fix compilation error and warning)

---

include/boost/geometry/strategies/normalize.hpp
include/boost/geometry/strategies/spherical/point_in_point.hpp
include/boost/geometry/util/normalize_spheroidal_coordinates.hpp
include/boost/geometry/util/rational.hpp
test/algorithms/equals/equals_on_spheroid.cpp
test/algorithms/overlay/get_turns_linear_linear_geo.cpp
test/algorithms/set_operations/difference/difference_linear_linear.cpp
test/util/rational.cpp

Currently when points (180,0) and (-180,0) are tested for equality (in spherical or geographic systems) we are getting the expected result which is true. 
However, if the points are in radians instead of degrees the accuracy of the representation of pi/2 or the conversion from 180 degrees to radians could result in wrong results of equals (see added tests in this PR for details). 
This PR fixes this issue by relaxing conditions in normalization of spheroidal coordinates.

Relax half period check in spheroidal normalization

---

include/boost/geometry/algorithms/detail/overlay/check_enrich.hpp
include/boost/geometry/strategies/geographic/distance_cross_track_box_box.hpp
include/boost/geometry/strategy/cartesian/side_by_triangle.hpp
include/boost/geometry/util/promote_integral.hpp

Fixes: #629
This was a long standing warning where we were pinged about several times.
I think this is the best solution at the moment. However, it solves one case. There is the message:
>This pattern of select_most_precise<double,...> is pretty common, and I have found the same warning being produced in other parts of boost that do the same thing when using with std::int64_t.
I cannot fix all of that now, it first have to wait at least for the big improvement in intersections.
Then we probably should fix it in `select_most_precise` itself.
Please give me your opinions.
If possible it should be included in `1.88`

fix: avoid warnings for coordinate conversions and unused parameters

---

.github/workflows/minimal.yml

Retire ubuntu 20.04 from github actions. This force us to also remove clang versions > 6 and gcc < 7, since it is not straightforward to install them in ubuntu 22.04. In particular, if one tries to import the ubuntu 18 (bionic) archives then `apt install` reaches an impossible situation when trying to install older versions (e.g. clang 5.0) due to unmet dependencies.

Retire ubuntu 20.04

---

test/algorithms/buffer/CMakeLists.txt
test/algorithms/buffer/buffer_linestring_geo.cpp

addresses: #1403
The Aimes test cases are a set of complex real life features which are not yet totally robust for geographic buffers.

test: exclude failing aimes test cases

---

include/boost/geometry/algorithms/detail/overlay/assign_parents.hpp
include/boost/geometry/algorithms/detail/overlay/follow_linear_linear.hpp
include/boost/geometry/algorithms/detail/overlay/range_in_geometry.hpp
include/boost/geometry/algorithms/detail/relate/follow_helpers.hpp
include/boost/geometry/core/access.hpp
include/boost/geometry/formulas/spherical.hpp
include/boost/geometry/index/detail/utilities.hpp

I am working on converting a large scientific library (https://www.dealii.org) that builds on BOOST to C++20 modules, see https://github.com/dealii/dealii/issues/18071. As part of this effort, I have to find ways to "wrap" BOOST into a module partition, something that will look like this file: https://github.com/bangerth/dealii/blob/cxx-modules/cxx20-modules/interface_module_partitions/boost.ccm 
Wrapping works by "exporting" certain BOOST names via `using` declarations, but the targets of these `using` declarations can only be names that have "external linkage". This excludes `static` variables and functions because they have "internal linkage". GCC 15 also requires that all names *referenced* by entities I want to export *also* have external linkage, and this turns up quite a large …

Avoid static variables and functions in header files.

---

.github/workflows/minimal.yml

Closes https://github.com/boostorg/geometry/issues/1223

[ci] Fix mscv versions

---

include/boost/geometry/algorithms/detail/overlay/graph/traverse_graph.hpp

See #1411 (last commit) where it was discovered and fixed.
This commit is meant to be merged to `1.89` beta

fix: avoid stack overflow in traverse

---

doc/concept/polyhedral_surface.qbk
include/boost/geometry/algorithms/detail/is_valid/implementation.hpp
include/boost/geometry/algorithms/detail/is_valid/interface.hpp
include/boost/geometry/algorithms/detail/is_valid/polyhedral_surface.hpp
include/boost/geometry/algorithms/detail/overlay/graph/assign_counts.hpp
include/boost/geometry/algorithms/detail/overlay/graph/detect_biconnected_components.hpp
include/boost/geometry/algorithms/validity_failure_type.hpp
include/boost/geometry/geometries/concepts/polyhedral_surface_concept.hpp
include/boost/geometry/geometries/polyhedral_surface.hpp
include/boost/geometry/strategies/cartesian/side_3d_rounded_input.hpp
include/boost/geometry/strategies/cartesian/side_rounded_input.hpp
include/boost/geometry/strategies/relate3/cartesian.hpp
include/boost/geometry/strategies/relate3/services.hpp
test/algorithms/is_valid.cpp
test/geometries/CMakeLists.txt
test/geometries/Jamfile
test/geometries/polyhedral_surface.cpp
test/geometries/polyhedral_surface_fail.cpp

This PR introduces support for the `is_valid` algorithm for polyhedral surface geometries. A polyhedral_surface is a 3D composite geometry formed by a collection of polygonal faces that meet at shared edges. The implementation follows the OGC Simple Features Specification and introduces structural and topological checks for polyhedral surfaces.
The following properties should hold (following OGC standard):
- Contiguity: All polygon patches must form a connected surface via shared boundary segments.
- Shared Edges: Shared boundaries must be finite LineStrings used in at most two polygons.
- Orientation: Shared boundaries must be traversed in opposite directions by adjacent polygons; global orientation must be consistent.
Six new validity failure types has been introduced that reflect the …

feat: Implement is_valid algorithm for polyhedral surfaces
